feat(delay): create composition functions
vuetifyjs/vuetify pull request #10412
Opened 2020-02-01 10:31 UTC by jacekkarczmarczyk

## Description
delayable mixin

## Motivation and Context
Vue 3

## How Has This Been Tested?
was not

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-10-24 13:11 UTC, nekosaur requested changes

2020-10-24 13:11 UTC, nekosaur commented on packages/vuetify/src/composables/delay.ts
> +export function delayProps (
```suggestion
export function makeDelayProps (
```

2020-10-24 13:11 UTC, nekosaur commented on packages/vuetify/src/composables/delay.ts
> +  openDelay: number | string
```suggestion
  closeDelay?: number | string
  openDelay?: number | string
```

2020-10-26 22:40 UTC, johnleider requested changes

2020-10-26 22:40 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/delay.spec.ts
> +import { mount } from '@vue/test-utils'
```suggestion
// Utilities
import { mount } from '@vue/test-utils'
```

2020-10-26 22:40 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/delay.spec.ts
> +    await wait(30)
```suggestion
    await wait(30)

```

2020-10-26 22:40 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/delay.spec.ts
> +    await wait(30)
This is a superfluous suggestion

2020-10-26 22:40 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/delay.spec.ts
> +
```suggestion
// Globals
import { IN_BROWSER } from '../../util/globals'

```

2020-10-26 22:40 UTC, johnleider commented on packages/vuetify/src/composables/delay.ts
> +  const runDelayFactory = (prop: keyof DelayProps) => (): Promise<boolean> => {
```suggestion
  if (!IN_BROWSER) return
  
  const runDelayFactory = (prop: keyof DelayProps) => (): Promise<boolean> => {
```

2021-02-15 20:04 UTC, johnleider approved these changes

2021-03-01 20:24 UTC, merged