Treeview keyboard
vuetifyjs/vuetify pull request #11780
Opened 2020-07-02 19:34 UTC by deviousreality

## Description
Added ability to transverse the Treeview component with the keyboard. Aria markup was added to help
with screenreaders.
fixes #10796 

## Motivation and Context
Treeview was missing keyboard and accessibility markup. Adding these feature improves the ability to use Vuetify + Treeview with clients who require WCAG AA support 

## How Has This Been Tested?
- Added unit tests for VTreeview component for keyboard navigation. The tests verify tabindex placement as the user transverse the tree
- Tested in playground and in Vuetify Docs

## Markup:
<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [X ] The PR title is no longer than 64 characters.
- [ X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [X ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-11-11 06:49 UTC, KaelWD requested changes

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +        (this.$refs.treeviewnode as HTMLElement).focus()
Define refs on line 25 and remove the assertion

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +    handkeKey (event: KeyboardEvent): void {
```suggestion
    handleKey (event: KeyboardEvent): void {
```

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +      if ([keyCodes.down].includes(keyCode)) return moveDown.call(this, event)
- Includes on a one-element array is redundant
- Arrow functions use lexical `this`, they can be called directly.

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +        (this.treeview.$refs.treeview as HTMLElement).scrollTop = top
Add ref type

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeview.ts
> +          const getNextTopNode = function (searchKey: string | number,
```suggestion
          const getNextTopNode = function (
            searchKey: string | number,
```

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeview.ts
> +            nodes: Record<string | number, NodeState>, parents: string|number[]): string | number {
```suggestion
              nodes: Record<string | number, NodeState>,
              parents: string|number[]
            ): string | number {
```

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeview.ts
> +        const getLastOpenedChildNode = (searchKey: string | number, nodes: Record<string | number, NodeState>): string | number => {
This function is redundant, it's just being called straight away then discarded.

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeview.ts
> +    updateFocus (this: any, key: string | number, hasFocus: boolean): void {
Why `this: any`?

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeview.ts
> +    updateOpen (this: any, key: string | number, isOpen: boolean) {
And here

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +              this.$nextTick(function () {
`return this.$nextTick()` then chain the promise instead of nesting callbacks

2020-11-11 06:49 UTC, KaelWD commented on packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
> +              this.$nextTick(function () {
- Use an arrow function
- Is this supposed to be called after `checkChildren` resolves?

2020-12-19 17:30 UTC, johnleider commented
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

2020-12-19 17:30 UTC, closed without merging