feat(VDataTable): Add shift key logic for multiple selection
vuetifyjs/vuetify pull request #11921
Opened 2020-07-23 17:02 UTC by Aramis13

## Description
Add a listener for shift key press.
Add logic for selecting multiple check-boxes.

## Motivation and Context
Feature request #9958.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ x] The PR title is no longer than 64 characters.
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-11-11 06:56 UTC, KaelWD requested changes

2020-11-11 06:56 UTC, KaelWD commented on packages/vuetify/src/components/VDataIterator/VDataIterator.ts
> +    shiftKeyDown: false as boolean,
```suggestion
    shiftKeyDown: false,
```

2020-11-11 06:56 UTC, KaelWD commented on packages/vuetify/src/components/VDataIterator/VDataIterator.ts
> +      if (e.keyCode !== 16) return
```suggestion
      if (e.keyCode !== keyCodes.shift) return
```

2020-11-14 11:39 UTC, nekosaur requested changes
There are a few behaviors here that I feel are not standard when it comes to shift selecting.

1. Select last entry without holding shift. Then select first entry while holding shift. My expectation here is that it would select from last entry to first entry, but that is not the case.

2. Select first entry without holding shift. Then select last entry while holding shift. The entire page is select. Then while still holding shift, select a middle entry. Here I would expect that everything from middle entry to the last entry would be deselected, but the opposite happens where everything from first entry to middle entry is deselected.

2020-11-18 20:31 UTC, nekosaur commented on packages/vuetify/src/components/VDataIterator/VDataIterator.ts
> +        }
Try to refactor this into something more DRY. The only difference between the ifs is the for loop definition

2021-02-20 09:12 UTC, nekosaur approved these changes

2021-04-24 15:07 UTC, merged