feat: add proxy composable
vuetifyjs/vuetify pull request #12347
Opened 2020-10-04 14:54 UTC by nekosaur

## Description
Composable can be used to easily set up two-way sync of prop, while keeping internal value state if prop is not defined. If prop is defined it will always be the source of truth.

## Motivation and Context
This attempts to solve some issues we've had when trying to make our components work both with and without setting a v-model. Sometimes internal values have been overriding values set through the prop.

## How Has This Been Tested?
unit tests and playground

## Markup:

<details>

```vue
<template>
  <div>
    <foo
      text="value prop defined, no change handler"
      :value="foo"
    />
    <foo
      text="value prop defined, with change handler"
      :value="bar"
      @update:value="v => bar = v"
    />
    <foo
      text="no value prop defined, no change handler"
    />
    <foo
      text="no value prop defined, change handler"
      @update:value="v => log(`no value prop defined, change handler triggered with ${v}`)"
    />
    <button @click="() => defined = !defined">switch if defined, currently {{ defined ? 'yes' : 'no' }}</button>
    <foo v-bind="props" />
  </div>
</template>

<script lang="ts">
  import { h, defineComponent, ref, computed } from 'vue'
  import { useProxiedModel } from '../src/composables'

  const Foo = defineComponent({
    props: {
      text: String,
      value: {
        type: String,
        default: 'x',
      },
    },
    setup (props, context) {
      const syncedValue = useProxiedModel(props, context, 'value', '')

      return () => h('div', {
        onClick: () => {
          syncedValue.value = syncedValue.value === 'x' ? ' ' : 'x'
        },
      }, [props.text, ' - ', '[', syncedValue.value, ']'])
    },
  })

  export default defineComponent({
    components: {
      Foo,
    },
    setup () {
      const foo = ref('x')
      const bar = ref('x')
      const asd = ref('y')

      const defined = ref(false)

      const props = computed(() => {
        const obj: Record<string, any> = {
          text: 'value prop dynamically defined',
          'onUpdate:value': (v: any) => console.log(v),
        }
        if (defined.value) {
          obj.value = asd.value
        }
        return obj
      })

      return {
        foo,
        bar,
        defined,
        props,
        log: v => console.log(v),
      }
    },
  })
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-10-20 15:36 UTC, jacekkarczmarczyk commented on packages/vuetify/src/util/helpers.ts
>  export function kebabCase (str: string): string {
`string | null | undefined` or remove `(str || '')` and null checking in tests

2020-10-20 16:38 UTC, johnleider requested changes

2020-10-20 16:38 UTC, johnleider commented on packages/vuetify/src/composables/proxiedModel.ts
> +import { ref, computed, getCurrentInstance, SetupContext, Ref } from 'vue'
```suggestion
// Utilities
import { ref, computed, getCurrentInstance, SetupContext, Ref } from 'vue'
```

2020-10-20 16:38 UTC, johnleider commented on packages/vuetify/src/util/__tests__/helpers.spec.ts
> +// import Vue from 'vue/dist/vue.common.js'
```suggestion
```

2020-10-20 16:38 UTC, johnleider commented on packages/vuetify/src/util/__tests__/helpers.spec.ts
> +  kebabCase,
move up one line, alpha ordering 😠

2020-10-20 16:38 UTC, johnleider commented on packages/vuetify/src/util/__tests__/helpers.spec.ts
> +  it('should convert string to kebab case', () => {
should use it.each

2020-10-20 16:38 UTC, johnleider commented on packages/vuetify/src/util/__tests__/helpers.spec.ts
> +    expect(kebabCase(null)).toBe('')
should use it.each

2020-10-20 16:46 UTC, jacekkarczmarczyk commented on packages/vuetify/src/composables/proxiedModel.ts
> +      context.emit(`update:${prop}`, transformOut(newValue))
`vm.emit()`?

2020-10-20 16:56 UTC, jacekkarczmarczyk commented on packages/vuetify/src/util/__tests__/helpers.spec.ts
> +    expect(kebabCase('WhatIsThis')).toBe('what-is-this')
this test looks like repeated PascalCase test

2020-10-22 19:38 UTC, jacekkarczmarczyk approved these changes
i'd remove unrelated changes from PR and unnecessary !! in computed, but otherwise looks good

2020-10-23 11:15 UTC, KaelWD approved these changes

2020-10-23 11:17 UTC, merged