chore: move files from next repo
vuetifyjs/vuetify pull request #12344
Opened 2020-10-03 09:41 UTC by nekosaur

2020-10-07 19:23 UTC, johnleider requested changes

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +  const arr = Array.isArray(type) ? type : [type]
could we use the `wrapInArray` helper function?

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +  return {
Could be a single line.

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +    const propOptions = (props[key] as any)
```suggestion
    const propOptions = (props[key] as any)

```

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +    const vm = getCurrentInstance()
```suggestion
    const vm = getCurrentInstance()

```

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +      console.warn('Unable to get current component instance when generating default prop value')
```suggestion
      console.warn('Unable to get current component instance when generating default prop value')

```

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +    }
```suggestion
    }

```

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +  const defaults = vuetify.defaults[key] as any
```suggestion
  const defaults = vuetify.defaults[key] as any

```

2020-10-07 19:23 UTC, johnleider commented on packages/vuetify/src/framework.ts
> +  if (defaults == null) return null
```suggestion
  if (defaults == null) return null

```

2020-10-15 08:08 UTC, KaelWD approved these changes

2020-10-15 08:09 UTC, merged