fix(VCarousel): incorrect transition direction when using touch
vuetifyjs/vuetify pull request #12357
Opened 2020-10-05 17:58 UTC by nekosaur

## Description
using touch would result in incorrect transition when looping around

## Motivation and Context
closes #11280>

## How Has This Been Tested?

## Markup:

<details>

```vue
<template>
  <div>
    <v-switch
      v-model="$vuetify.rtl"
      label="RTL"
    />
    <v-btn @click="foo = foo - 1 < 0 ? slides.length - 1 : foo - 1">prev</v-btn>
    <v-btn @click="foo = foo + 1 >= slides.length ? 0 : foo + 1">next</v-btn>
    <v-carousel
      v-model="foo"
      height="400"
      hide-delimiter-background
      show-arrows-on-hover
    >
      <v-carousel-item
        v-for="(slide, i) in slides"
        :key="i"
      >
        <v-sheet
          :color="colors[i]"
          height="100%"
        >
          <v-row
            class="fill-height"
            align="center"
            justify="center"
          >
            <div class="display-3">{{ slide }} Slide</div>
          </v-row>
        </v-sheet>
      </v-carousel-item>
    </v-carousel>

    <v-carousel
      height="400"
      hide-delimiter-background
      show-arrows-on-hover
      reverse
    >
      <v-carousel-item
        v-for="(slide, i) in slides"
        :key="i"
        :value="`value_${i}`"
      >
        <v-sheet
          :color="colors[i]"
          height="100%"
        >
          <v-row
            class="fill-height"
            align="center"
            justify="center"
          >
            <div class="display-3">{{ slide }} Slide</div>
          </v-row>
        </v-sheet>
      </v-carousel-item>
    </v-carousel>

    <v-carousel
      height="400"
      hide-delimiter-background
      show-arrows-on-hover
      vertical
    >
      <v-carousel-item
        v-for="(slide, i) in slides"
        :key="i"
        :value="`value_${i}`"
      >
        <v-sheet
          :color="colors[i]"
          height="100%"
        >
          <v-row
            class="fill-height"
            align="center"
            justify="center"
          >
            <div class="display-3">{{ slide }} Slide</div>
          </v-row>
        </v-sheet>
      </v-carousel-item>
    </v-carousel>
  </div>
</template>

<script>
  export default {
    data: () => ({
      foo: 0,
      colors: [
        'indigo',
        'warning',
        'pink darken-2',
        'red lighten-1',
        'deep-purple accent-4',
      ],
      slides: [
        'First',
        'Second',
        'Third',
        'Fourth',
        'Fifth',
      ],
    }),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-10-07 19:56 UTC, johnleider requested changes

2020-10-07 19:56 UTC, johnleider commented on packages/vuetify/src/components/VWindow/VWindow.ts
>      reverse: {
Any reason against doing `reverse: Boolean`?

2020-10-07 20:27 UTC, nekosaur commented on packages/vuetify/src/components/VWindow/VWindow.ts
>      reverse: {
no

2020-10-27 16:17 UTC, johnleider requested changes

2020-10-27 16:17 UTC, johnleider commented on packages/vuetify/src/components/VWindow/VWindow.ts
> +      default: false,
Booleans are false by default.

2020-10-27 16:17 UTC, johnleider commented on packages/vuetify/src/components/VWindow/VWindow.ts
> +            click,
could be on 1 line on 152

2020-11-24 18:45 UTC, MajesticPotatoe approved these changes
LG!

2020-11-24 18:45 UTC, merged