feat(ad): add utm metadata on ads
vuetifyjs/vuetify pull request #12439
Opened 2020-10-18 15:16 UTC by jpntex

## Description

Add UTM source and medium on Vuetify ads

## Motivation and Context

Better Vuetify ads efficiency tracking

## How Has This Been Tested?

Visually | GA

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-10-18 15:16 UTC, KaelWD commented on packages/docs/src/components/ad/Bsa.vue
> -  #bsa-native
Are these style changes intentional?

2020-10-18 15:24 UTC, jpntex commented on packages/docs/src/components/ad/Bsa.vue
> -  #bsa-native
No they are not, rolling back

2020-10-19 20:30 UTC, johnleider requested changes

2020-10-19 20:30 UTC, johnleider commented on packages/docs/src/components/doc/PremiumThemes.vue
> +          :href="`https://store.vuetifyjs.com/products/${product.handle}?utm_source=vuetifyjs.com&utm_medium=themes`"
```suggestion
          :href="`https://store.vuetifyjs.com/products/${product.handle}/?utm_source=vuetifyjs.com&utm_medium=themes`"
```

2020-10-19 20:46 UTC, johnleider approved these changes

2020-10-20 03:16 UTC, merged