wip: v-icon and icon composable
vuetifyjs/vuetify pull request #12741
Opened 2020-12-07 20:58 UTC by nekosaur

## Description
Very much work in progress. Looking for feedback on new VIcon component(s) and icon composable (VIcon.ts, composables/icon.ts, dev/index.js)

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-12-08 07:06 UTC, KaelWD commented on packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
> +<i class="v-icon notranslate  v-size--default M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"
SVG path in class?

2020-12-08 09:48 UTC, nekosaur commented on packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
> +<i class="v-icon notranslate  v-size--default M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"
The tests are not current

2020-12-21 18:17 UTC, johnleider requested changes
Can the duplicate properties between the difference class icons be DRYed up?

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/components/VIcon/index.ts
> +export { VLigatureIcon, VClassIcon, VSvgIcon } from './VIcon'
```suggestion
export { VClassIcon, VLigatureIcon, VSvgIcon } from './VIcon'
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/size.spec.ts
> +import { makeSizeProps, useSizeClass } from '../size'
```suggestion
import { makeSizeProps, useSize } from '../size'
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/size.spec.ts
> +    const { sizeClass } = useSizeClass(input)
```suggestion
    const { sizeClasses } = useSize(input)
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/__tests__/size.spec.ts
> +    expect(sizeClass.value).toStrictEqual(expected)
```suggestion
    expect(sizeClasses.value).toStrictEqual(expected)
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/size.ts
> +const predefinedSizes = ['x-small', 'small', 'default', 'large', 'x-large']
Should this be capitalized, similar to a global variable? I feel like this would be used in more than one place.

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/size.ts
> +  const sizeClass = computed(() => {
```suggestion
  const sizeClasses = computed(() => {
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/composables/size.ts
> +  return { sizeClass }
```suggestion
  return { sizeClasses }
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/components/VIcon/VIcon.ts
> +import { useIcon, makeSizeProps, useSizeClass } from '@/composables'
```suggestion
import { useIcon, makeSizeProps, useSize } from '@/composables'
```

2020-12-21 18:17 UTC, johnleider commented on packages/vuetify/src/components/VIcon/VIcon.ts
> +    const { sizeClass } = useSizeClass(props)
```suggestion
    const { sizeClasses } = useSize(props)
```

2020-12-21 18:40 UTC, nekosaur commented on packages/vuetify/dev/App.vue
> +  import Playground from './Playground.icons'
This is just WIP stuff, will be reverted before merge

2020-12-21 18:41 UTC, nekosaur commented
> Can the duplicate properties between the difference class icons be DRYed up?

Not sure what you're referring to here

2020-12-22 02:10 UTC, KaelWD commented on packages/vuetify/src/components/VIcon/VIcon.sass
> +      height: map-get($icon-sizes, $name)
x, y

2020-12-22 02:12 UTC, KaelWD commented on packages/vuetify/src/components/VIcon/VIcon.ts
> +  inheritAttrs: false,
Put that in eslint if you want it enforced.

2021-01-29 11:34 UTC, nekosaur commented
I'd like to get some feedback from @jacekkarczmarczyk and @KaelWD if possible.

Usage
```
createVuetify({
  icons: {
    defaultSet: 'mdi',
    sets: {
      mdi: {
        component: () => ...,
        aliases: {
          close: 'mdi-close'
        }
      },
      fa5: {
        component: () => ...,
        aliases: { ... }
      }
    }
  }
})
```

```
<v-icon icon="mdi-close"/> <- uses default set
<v-icon icon="mdi:mdi-home/"> <- uses specified set

<v-icon icon="$close"/> <-- uses default set alias
<v-icon icon="mdi:$close"/> <-- uses specified set alias

<v-icon icon="fa5:fas fa-close"/> <-- uses specified set
<v-icon icon="fa5:$close"/> <-- uses specified set alias

<v-icon icon="IconComponent"/> <-- renders component inside v-icon
```

2021-02-06 13:22 UTC, nekosaur commented
Things still not finished

- [ ] tests

2021-02-10 12:20 UTC, KaelWD commented on packages/vuetify/src/composables/icons.ts
> +import { VClassIcon, VComponentIcon, VSvgIcon } from '@/components'
Import from `@/components/VIcon` so we aren't pulling in every component in dev. This is recursive btw, might not be ideal.

2021-02-15 19:16 UTC, johnleider approved these changes

2021-02-17 08:40 UTC, KaelWD approved these changes

2021-02-17 08:41 UTC, merged