fix(VTextField): align dense mode text field prefix and content
vuetifyjs/vuetify pull request #12759
Opened 2020-12-09 21:40 UTC by juddfranklin1

fixes #12743

## Description

fixes #12734

## Motivation and Context

(https://github.com/vuetifyjs/vuetify/issues/12743)
## How Has This Been Tested?

Since this change was strictly a matter of specific sass rules, I tested using Chrome inspector to confirm style application and visually confirming that elements are aligned precisely in the proper context

## Markup:

<details>

```vue
<template>
  <v-container>
    
    <v-text-field
            dense
            label="Amount"
            value="10.00"
            prefix="0x"
          ></v-text-field>
  </v-container>
</template>

<script>
  import VTextField from '../src/components/VTextField/index.ts';

  export default {
    data: () => ({
    //
    }),
    components:{
      'v-text-field': VTextField
    }
  }
</script>

```
</details>

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ x] The PR title is no longer than 64 characters.
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-12-15 20:41 UTC, MajesticPotatoe reviewed
For text content this looks good, seems that `v-text-field` label is also affected by this issue as well.

2020-12-16 01:18 UTC, juddfranklin1 commented
> For text content this looks good, seems that `v-text-field` label is also affected by this issue as well.

@MajesticPotatoe Ok, I applied a SASS fix that fixes the alignment of the label when it appears where the input value would appear.

2020-12-19 22:20 UTC, johnleider commented
The only issue here is the label positioning. It also exposes an issue with the inner appended icon that appears to have unnecessary margin applied to it, at least in the case of `v-select`.

Working codepen: https://codepen.io/johnjleider/pen/VwKWJQX

2020-12-20 20:28 UTC, juddfranklin1 commented
Thanks for the detailed Codepen @johnleider. I have removed the additional margin-top on the icon:
Playground code below. Does my previous commit on this PR effectively fix the label positioning?
```
<template>
  <v-container>
    <v-row>
      <v-text-field
        label="Amount"
        value="10.00"
        prefix="0x"
        suffix="2x"
      ></v-text-field>
      <v-select
        label="Amount"
        value="10.00"
        suffix="2x"
        prefix="0x"
        :items="['10.00']"
      ></v-select>
      <v-combobox
        label="Amount"
        value="10.00"
        prefix="0x"
        suffix="2x"
        :items="['10.00']"
      ></v-combobox>
      <v-autocomplete
        label="Amount"
        value="10.00"
        prefix="0x"
        suffix="2x"
        :items="['10.00']"
      ></v-autocomplete>
    </v-row>
    <v-row>
      <v-text-field
        dense
        label="Amount"
        value="10.00"
        suffix="2x"
        prefix="0x"
      ></v-text-field>
      <v-select
        dense
        label="Amount"
        value="10.00"
        suffix="2x"
        prefix="0x"
        :items="['10.00']"
      ></v-select>
      <v-combobox
        dense
        label="Amount"
        value="10.00"
        suffix="2x"
        prefix="0x"
        :items="['10.00']"
      ></v-combobox>
      <v-autocomplete
        dense
        label="Amount"
        value="10.00"
        suffix="2x"
        prefix="0x"
        :items="['10.00']"
      ></v-autocomplete>
    </v-row>
    <v-row>
      <v-text-field
        label="Amount"
        prefix="0x"
        suffix="2x"
      ></v-text-field>
      <v-select
        label="Amount"
        prefix="0x"
        suffix="2x"
      ></v-select>
      <v-combobox
        label="Amount"
        prefix="0x"
        suffix="2x"
      ></v-combobox>
      <v-autocomplete
        label="Amount"
        suffix="2x"
        prefix="0x"
      ></v-autocomplete>
    </v-row>
    <v-row>
      <v-text-field
        dense
        suffix="2x"
        label="Amount"
        prefix="0x"
      ></v-text-field>
      <v-select
        dense
        label="Amount"
        suffix="2x"
        prefix="0x"
      ></v-select>
      <v-combobox
        dense
        label="Amount"
        suffix="2x"
        prefix="0x"
      ></v-combobox>
      <v-autocomplete
        dense
        label="Amount"
        prefix="0x"
        suffix="2x"
      ></v-autocomplete>
    </v-row>

    <v-row>
      <p class="text-h6">Below I have included the contents of the Codepen for previously resolved issue <a href="https://github.com/vuetifyjs/vuetify/issues/11011" target="_blank">11011</a>. The current fix removes code originally added to resolve #11011.</p>
    </v-row>

    <v-row>
      <v-col cols="12" sm="6">
        <v-text-field
          outlined
          label="Prepend inner"
          prepend-inner-icon="place"
          clearable
          value="Test"
        ></v-text-field>
      </v-col>
      <v-col cols="12" sm="3">
        <v-text-field
          outlined
          label="Prepend inner"
          prepend-inner-icon="place"
          clearable
          value="Test"
          dense
        ></v-text-field>
      </v-col>
      <v-col cols="12" sm="3">
        <v-text-field
          outlined
          label="Prepend inner"
          prepend-inner-icon="place"
          clearable
          value="Test"
          dense
          class="oldStyle"
        ></v-text-field>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>

  export default {
    data: () => ({
    //
    }),
  }
</script>

```

2020-12-29 18:34 UTC, juddfranklin1 commented
Playground for this PR has been updated.

2020-12-31 19:58 UTC, MajesticPotatoe requested changes
looking at this, there's seems to be some inconsistency with the suffix as well. believe you need to add the proper top/bottom padding to the suffix as well as line-height so that all three (prefix/input/suffix) are aligned. Seems like dense mode is also missing the proper right padding on the prefix.
![1](https://user-images.githubusercontent.com/27827979/103424055-3f97be00-4b78-11eb-9fd4-251467d934d0.png)
![2](https://user-images.githubusercontent.com/27827979/103424056-40305480-4b78-11eb-917d-3dedba4cb908.png)
![3](https://user-images.githubusercontent.com/27827979/103424057-40305480-4b78-11eb-884c-d3988fb23b69.png)

2021-01-01 08:02 UTC, juddfranklin1 commented
> looking at this, there's seems to be some inconsistency with the suffix as well. believe you need to add the proper top/bottom padding to the suffix as well as line-height so that all three (prefix/input/suffix) are aligned. Seems like dense mode is also missing the proper right padding on the prefix.

@MajesticPotatoe I was operating with the idea that the existing code intentionally removed horizontal space in dense mode. Restoring the padding as you suggest looks more readable to me. The suffix is also lacking left padding in dense mode. Do you think I should add that, too?

2021-01-04 15:30 UTC, MajesticPotatoe commented
@juddfranklin1 
> The suffix is also lacking left padding in dense mode. Do you think I should add that, too?

I would say yes for consistency sake.

2021-01-05 21:31 UTC, MajesticPotatoe approved these changes

2021-01-05 21:32 UTC, merged