fix(VAlert): VAlert Always in Dark Mode
vuetifyjs/vuetify pull request #12782
Opened 2020-12-14 09:41 UTC by NabeelAhmed314

fixes #11021

VAlert always stays in dark mode even with theme.dark = false. I have changed some code to make it to dark mode trigger according to theme.dark.

## Description
Changed the conditions of triggring dark mode that will work according to the themes dark mode.

Resolves #11021

## Motivation and Context
In order to start phase # 1 of Vuetify Titan all bugs with components had to be resolved.
Resolves Following Issue.
#11021

## How Has This Been Tested?
This has been tested visually.

## Markup:

<details>

```
<template>
  <div style="padding: 20px">
    <div>
      <v-alert
        dark
        text
        type="success"
      >
        I'm a success alert.
      </v-alert>

      <v-alert
        text
        type="info"
      >
        I'm an info alert.
      </v-alert>

      <v-alert
        text
        type="warning"
      >
        I'm a warning alert.
      </v-alert>

      <v-alert
        text
        type="error"
      >
        I'm an error alert.
      </v-alert>
    </div>
  </div>
</template>

<script>
  export default {
    data: () => ({
      showDialog: () => true,
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-12-18 10:26 UTC, NabeelAhmed314 commented
Kindly Review Pull Request!!

2020-12-19 20:29 UTC, johnleider requested changes
I do not like how this currently operates but I'm hesitant to make any changes here, especially ones that are so overarching.

2020-12-19 20:29 UTC, johnleider commented on packages/vuetify/src/components/VAlert/VAlert.ts
> +      if (this.dark === true) {
This is exactly the same as the themeable mixin that `v-alert` already extends. https://github.com/vuetifyjs/vuetify/blob/b1c3f81bb62bc218b1c18236f7252412722b32fc/packages/vuetify/src/mixins/themeable/index.ts#L51

2020-12-19 20:29 UTC, johnleider commented on packages/vuetify/src/components/VSheet/VSheet.sass
> +  background-color: map-get($material, 'cards') !important
What is the reason for making this !important? `v-sheet` is used by a ton of components, this is a recipe for disaster.

2021-01-05 23:08 UTC, johnleider commented
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

2021-01-05 23:08 UTC, closed without merging