Feat/v date picker first&last classes
vuetifyjs/vuetify pull request #12855
Opened 2020-12-29 16:22 UTC by joelpro2

## Description

Added class v-date-picker__firstInRange to the first day in range
Added class v-date-picker__lastInRange to the last day in range
Added test for both

resolves #12851 

## Motivation and Context
This change allows devs to style the threshold days
 #12851 

## How Has This Been Tested?
unit

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <v-date-picker
      v-model="dates"
      range
    ></v-date-picker>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      dates: []
    }),
  }
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2020-12-29 17:08 UTC, jacekkarczmarczyk requested changes
1. please rebase properly, pr contains some unrelated commits
2. we don't use capital letters in class names
3. it applies classes to the button, i think it's better if it applied classes to the `<td>`
4. afair dates in v-model may be sorted descending if you click the last date of a range as first (didn't check it though)
5. don't you need these classes also for month/year selector?

2020-12-29 20:28 UTC, joelpro2 commented
> 2. we don't use capital letters in class names -> How would you call it then?
> 3. it applies classes to the button, i think it's better if it applied classes to the `<td>` -> i'm applying classes where you are
> 4. afair dates in v-model may be sorted descending if you click the last date of a range as first (didn't check it though) ->this is for people to decide, in my project i sort the array but i think that may be cases that the beggining of the range may not be the oldest date.
> 5. don't you need these classes also for month/year selector? -> Maybe for the month.

2020-12-30 10:47 UTC, jacekkarczmarczyk commented
> > 1. we don't use capital letters in class names.
> 
> How would you call it then?

kebab case:
`some-block__some-element--some-modifier`

> > 1. it applies classes to the button, i think it's better if it applied classes to the `<td>`
> 
> I'm applying classes where you are

I know but i think that applying it to `<td>` would be more flexible for styling

> > 1. afair dates in v-model may be sorted descending if you click the last date of a range as first (didn't check it though)
> 
> This is for people to decide, in my project i sort the array but i think that may be cases that the beggining of the range may not be the oldest date.

https://codepen.io/jkarczm/pen/xxEYZNd - select 31dec then 1dec and you'll end up with this
![image](https://user-images.githubusercontent.com/15625235/103346483-6250a680-4a94-11eb-9955-2e53a0c7dbc2.png)

2021-01-27 13:04 UTC, joelpro2 commented
Is this still missing something? @MajesticPotatoe @jacekkarczmarczyk

2021-01-27 18:33 UTC, jacekkarczmarczyk commented
@joelpro2 patience please ;) it's planned for 2.5 which is not planned for the next few days

Looks like you're still missing applying the classes based on the order of dates in the array instead of order of the dates, so if the model contains `['2000-01-11', '2000-01-01']` the `2000-01-11` will be considered as first and `2000-01-01` as last, which imho isn't very helpful in terms of styling

2021-03-17 12:19 UTC, KaelWD commented
@joelpro2 are you still working on this?

2021-03-19 12:54 UTC, joelpro2 commented
> @joelpro2 are you still working on this?

No, like i said, the dates order should be up to developers to decide wherever the want dates ordered or not, and for the classes, it makes no sense to remove them from where the other styles are already applied, it would force developers to target more elements without a need.

2021-03-26 03:09 UTC, johnleider requested changes

2021-03-26 03:09 UTC, johnleider commented on packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
> +      isFirst: boolean, isLast: boolean) {
```suggestion
    genButtonClasses (
      isAllowed: boolean, 
      isFloating: boolean, 
      isSelected: boolean, 
      isCurrent: boolean,
      isFirst: boolean, 
      isLast: boolean,
     ) {
```

2021-03-26 03:09 UTC, johnleider commented on packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
> +        'v-date-picker--last_in_range': isLast,
```suggestion
        'v-date-picker--first-in-range': isFirst,
        'v-date-picker--last-in-range': isLast,
```

2021-03-26 03:09 UTC, johnleider commented on packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
> +          isFirst, isLast),
```suggestion
        class: this.genButtonClasses(
          isAllowed && !isOtherMonth, 
          isFloating, 
          isSelected, 
          isCurrent,
          isFirst, 
          isLast,
        ),
```

2021-03-26 13:30 UTC, johnleider requested changes

2021-03-26 13:30 UTC, johnleider commented on packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
> +      isLast: boolean
```suggestion
      isLast: boolean,
```

2021-03-26 13:30 UTC, johnleider commented on packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
> +          isLast
```suggestion
          isLast,
```

2021-06-14 18:30 UTC, johnleider commented
Pulse check. About to close this as stale.

2021-06-14 20:50 UTC, joelpro2 commented
> Pulse check. About to close this as stale.

sorry, thought it was ready to be merged

2021-06-14 21:00 UTC, johnleider approved these changes

2021-06-14 21:01 UTC, johnleider commented
One last once over from @KaelWD and we are good to go.

2021-06-15 07:37 UTC, KaelWD approved these changes

2021-06-15 13:25 UTC, jacekkarczmarczyk approved these changes

2021-06-15 13:26 UTC, merged