fix(VFileInput): prevent label and placeholder overlap
vuetifyjs/vuetify pull request #12891
Opened 2021-01-04 22:35 UTC by juddfranklin1

fixes #12864

## Description

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-container>
      <v-file-input
        accept="image/*"
        label="File input"
        placeholder="placeholder"
      ></v-file-input>
      <v-file-input
        accept="image/*"
        label="File input 2"
      ></v-file-input>
    </v-container>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
    //
    }),
  }
</script>

```
</details>

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x ] The PR title is no longer than 64 characters.
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x ] My code follows the code style of this project.
- [x ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-01-05 22:57 UTC, johnleider commented
I don't like the idea of adding a property to fix a bug. This should follow the same logic as `v-text-field` which was altered in https://github.com/vuetifyjs/vuetify/commit/ff500ba38592f3db1288c7552000260cedadd4e0 for a11y concerns.

2021-01-05 22:58 UTC, johnleider requested changes
I don't like the idea of adding a property to fix a bug. This should follow the same logic as `v-text-field` which was altered in https://github.com/vuetifyjs/vuetify/commit/ff500ba38592f3db1288c7552000260cedadd4e0 for a11y concerns.

2021-01-06 01:33 UTC, juddfranklin1 commented
> I don't like the idea of adding a property to fix a bug. This should follow the same logic as `v-text-field` which was altered in [ff500ba](https://github.com/vuetifyjs/vuetify/commit/ff500ba38592f3db1288c7552000260cedadd4e0) for a11y concerns.

This is helpful, thanks. I was a little uneasy about the approach, but didn't know a

2021-02-23 07:23 UTC, KaelWD approved these changes

2021-02-23 07:24 UTC, merged