fix(VCombobox):remove search val if matching item is selected from menu
vuetifyjs/vuetify pull request #12896
Opened 2021-01-05 11:45 UTC by vibhash-singh

## Description

Clear search string if the matching item is selected from the menu

## Motivation and Context

Done to fix #12523 

Combobox adds the search value to the selected items when an item is selected from the filtered menu. For other cases, it won't clear the search string from the Combobox even if the matching item is selected. 

The fix is to clear the search string whenever the item selection is made from the menu list which was filtered based on the search value.

## How Has This Been Tested?

1. Visually
2. Changed one unit test which covers this case. The unit test earlier was testing the fact that the search value will always remain in the Combobox even after the item selection. Changed it to test for the empty search input after selection is made.

## Markup:

<details>

```vue
<template>
  <div id="app">
    <v-app id="inspire">
      <v-container fluid>
        <v-combobox
          v-model="form.associates"
          placeholder="Associates"
          :items="associates"
          filled
          rounded
          clearable
          color="blue"
          :item-text="
              (item) => {
                  return (
                      item.NUMBER +
                      ' - ' +
                      item.FIRST_NAME +
                      ' ' +
                      item.LAST_NAME
                  );
              }
          "
          item-value="NUMBER"
          multiple
          chips
          deletable-chips
        >
        </v-combobox>
      </v-container>
    </v-app>
  </div>
</template>

<script>
export default {
   data: () => ({
    associates: [
      { NUMBER: '0', FIRST_NAME: 'Sample', LAST_NAME: 'User'},
      { NUMBER: '1', FIRST_NAME: 'John', LAST_NAME: 'Doe'},
      { NUMBER: '2', FIRST_NAME: 'Jane', LAST_NAME: 'Doe'},
      { NUMBER: '3', FIRST_NAME: 'Johnny', LAST_NAME: 'Appleseed'}
    ],
    form: {
      name: '',
      associates: []
    }
  })
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-02-09 19:10 UTC, johnleider commented
I tested this locally and the bug is still present. Can you re-check this please?

2021-02-09 19:11 UTC, johnleider requested changes
I tested this locally and the bug persists. Can you re-check this?

2021-02-10 05:24 UTC, vibhash-singh commented
@johnleider Made necessary changes. Please review

2021-02-23 07:36 UTC, KaelWD approved these changes

2021-02-23 07:36 UTC, merged