fix(VSelect) fix counter-value
vuetifyjs/vuetify pull request #13046
Opened 2021-02-03 17:21 UTC by Shinigami92

resolves #11584

## Motivation and Context
#11584

I'm the original author of the `counter-value` feature :wave: 

## How Has This Been Tested?
locally

## Markup:
<details>

```vue
<template>
  <v-container>
    <v-autocomplete
      v-model="value"
      :items="items"
      counter
      :counter-value="v => (v || '').replace(v, 'test123')"
    ></v-autocomplete>

    <v-autocomplete
      v-model="values"
      :items="items"
      counter
      :counter-value="v => v.join(', ') + 'test123'"
      multiple
    ></v-autocomplete>

    <v-text-field
      v-model="title"
      counter
      :counter-value="v => (v || '').replace(v, 'test123')"
    ></v-text-field>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    title: "",
    items: ["foo", "bar", "fizz", "buzz"],
    values: ["foo", "bar"],
    value: null
  })
};
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-02-09 20:37 UTC, johnleider requested changes
Thank you for your interest in improving Vuetify. Please create unit tests that correlate to the changes made in this request.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

2021-02-09 22:01 UTC, Shinigami92 commented
I tried to use `counterValue` using the `value` (_input_), but sadly the test doesn't see the value?! :confused:  
I think that has something to do with mocked/sync state?

Also tried to use e.g. `wrapper.setProps({ value: 'foo1', selectedItems: ['foo1'] })`
But nothing help

Do you know what I need to do to set a value and the `computedCounterValue` receives this value (`selectedItems`)?

2021-02-19 04:02 UTC, johnleider approved these changes

2021-02-19 08:12 UTC, Shinigami92 commented
@johnleider Thank you for providing better and simpler tests :+1: 
I will learn from your improvements and step by step can reach the wanted quality target requested by vuetify :smiley:  
I'm happy to contribute to Vuetify and the Vue community

2021-02-22 18:44 UTC, merged