fix(VSelect): specify min-height 10px
vuetifyjs/vuetify pull request #13101
Opened 2021-02-13 10:45 UTC by kenji7157

## Description

 fixes #13007

I fixed it so that VSelect baseline dose not changes when empty string is selected

## Motivation and Context

Without this fix, VSelect baseline would change when empty string is selected.

## How Has This Been Tested?

visually
---
**before behavior**  
![Kapture 2021-02-13 at 19 40 40](https://user-images.githubusercontent.com/18192657/107847969-60b82380-6e33-11eb-8284-c1f60b39d09a.gif)

**after behavior**  
![Kapture 2021-02-13 at 19 38 27](https://user-images.githubusercontent.com/18192657/107847937-1767d400-6e33-11eb-9b5b-919cb207ce14.gif)

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-row align="baseline">
      <v-col>
        Some label
      </v-col>
      <v-col cols="10">
        <v-select
          value="Item 2"
          :items="items"
          hide-details
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data: () => {
      return { items: ['', 'Item 2', 'Item 3'] }
    },
  }
</script>

```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [X] The PR title is no longer than 64 characters.
- [X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [X] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-02-13 15:42 UTC, kenji7157 commented
Please let me know if there is something more that needs to be done.

2021-03-16 00:41 UTC, johnleider requested changes
Add a variable to `VSelect/_variables.scss`:

```scss
$select-selections-min-height: .625rem !default;
```

2021-03-16 00:41 UTC, johnleider commented on packages/vuetify/src/components/VSelect/VSelect.sass
> +    min-height: 10px
```suggestion
    min-height: $select-selections-min-height
```

2021-03-31 21:22 UTC, johnleider approved these changes

2021-03-31 21:38 UTC, merged