feat(styles): remove v-application prefix on styles
vuetifyjs/vuetify pull request #13609
Opened 2021-05-06 18:05 UTC by nekosaur

## Description

remove v-application prefix to styles. also removes v-application specific styling on code, kbd, ul, ol, p

## Motivation and Context

utility/helper classes won't work in teleported content if they have prefix

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-05-06 20:57 UTC, johnleider requested changes
Were we still going to keep the code styles and make them optional?

2021-05-06 20:57 UTC, johnleider commented on packages/vuetify/src/styles/elements/_typography.sass
> +.display-4
this entire file can actually go away, as well as the loop in `settings/variables.scss` to make the new typography names backwards compatible.

2021-05-06 21:52 UTC, nekosaur commented
can't say I'm a fan of kbd and code as components, but if we really need to provide them styled it's probably the least ugly solution

2021-05-08 20:58 UTC, johnleider approved these changes

2021-05-09 12:57 UTC, merged