feat: update v-pagination to v3
vuetifyjs/vuetify pull request #13600
Opened 2021-05-04 21:16 UTC by nekosaur

## Description

update v-pagination to v3

## Breaking changes
- TODO

## TODO
- finish tests
- update documentation

## Motivation and Context

v3

## How Has This Been Tested?

playground and unit testse

## Markup:

<details>

```vue
<template>
  <v-app class="fill-height">
    <input type="checkbox" :checked="current === 'dark'" @change="current = current === 'dark' ? 'light' : 'dark'"> theme
    <input type="checkbox" :checked="rtl" @change="rtl = !rtl"> rtl
    <div class="pa-10">
      <v-locale-provider :rtl="rtl">
        
        
        
        
        <hr>
        rounded
        <v-pagination :length="12" v-model="page" rounded="0" />
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" rounded />
        <hr>
        density
        <v-pagination :length="12" v-model="page" density="compact" />
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" density="default" />
        <hr>
        size
        <v-pagination :length="12" v-model="page" size="x-small" />
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" size="x-large" />
        <hr>
        elevation
        <v-pagination :length="12" v-model="page" elevation="0" />
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" elevation="4" />
        <hr>
        show-first-last-page
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" show-first-last-page />
        <hr>
        disabled
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" disabled />
        <hr>
        total-visible
        <v-pagination :length="12" v-model="page" />
        <v-pagination :length="12" v-model="page" total-visible="5" />
        <hr>
        resize observer
        <div style="width: 400px">
          <v-pagination :length="12" v-model="page" />
        </div>
      </v-locale-provider>
    </div>
  </v-app>
</template>

<script>
  import { ref } from 'vue'
  import { useTheme } from '../src/composables/theme'

  export default {
    name: 'Playground',
    setup () {
      const show = ref(false)
      const theme = useTheme()
      const reverse = ref(false)
      const icon = ref('$close')
      const rtl = ref(false)
      const truncate = ref('end')
      const page = ref(1)

      return { show, current: theme.current, reverse, icon, rtl, truncate, page }
    },
  }
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-05-07 19:27 UTC, glen-84 commented
What do you think about using [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) to format the page numbers? (which would resolve #10085)

It would probably make sense to construct a single `NumberFormat` object somewhere (perhaps in the Lang/Locale service/composable), using the currently-set locale, and make that (or a proxy) available to components.

It's not only about larger numbers with separators, using a locale like `ar-EG` would actually render different numeric characters (f.e. `123` -> `١٢٣`).

2021-05-08 10:28 UTC, nekosaur commented
@glen-84 It is a good point about locales like arabic. Personally I think it looks very weird to show `1,000` (or in the case of my own locale, `1 000`) in a pagination component, but it probably should be the default behavior. With maybe a prop to disable the formatting?

2021-05-08 19:24 UTC, glen-84 commented
I agree that it should be the default, as it matches the default of `Intl.NumberFormat`.

You could consider an option that effectively sets `useGrouping` to `false`, if there is demand for that. The naming might be a bit awkward though ... something like `number-grouping` may sound as if it would group the buttons in some way, and I assume that you'd want to keep the prop names fairly short.

You could bikeshed on the naming, or just defer adding the option until someone actually asks for it. 🙃

2021-05-12 17:56 UTC, glen-84 commented
I guess #10085 can be added to the `fixes` list? 🙂

2021-05-30 17:56 UTC, johnleider requested changes
SASS structure needs updating and removal of default colors.

2021-05-30 17:56 UTC, johnleider commented on packages/vuetify/src/components/VBtn/VBtn.tsx
> +    color: {
What is this for?

2021-05-30 17:56 UTC, johnleider commented on packages/vuetify/src/components/VPagination/VPagination.tsx
> +    color: {
Remove default color.

2021-05-30 19:14 UTC, nekosaur commented
> removal of default colors.

I think we either need to have a discussion on how you think this should be done, or you can just push changes yourself.

2021-06-11 19:03 UTC, johnleider commented
I started working on a branch testing the removal of v-btn and some other minor refactoring. 
`feat/v3-pagination-remove-v-btn`

2021-06-28 19:49 UTC, johnleider commented
Requesting **Final** comments from @vuetifyjs/core-team

2021-06-28 19:51 UTC, johnleider approved these changes

2021-06-30 14:49 UTC, KaelWD approved these changes

2021-06-30 15:08 UTC, merged