fix(VListItem): color prop doesn't work #9285
vuetifyjs/vuetify pull request #13719
Opened 2021-05-28 08:34 UTC by Tofandel

## Description

Fixes #9285 by removing the !important keyword in the vuetify stylesheet

## Motivation and Context

It is currently not possible to change the color of a v-list-item via the `color` prop, it is only possible to do it via a tricky css rule with an `!important` keyword

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.

2021-05-28 09:00 UTC, Tofandel commented
Should the normal icon's color change as well maybe?

2021-05-28 09:07 UTC, KaelWD commented
Yes, but this was intentional so inactive items aren't highlighted (see https://vuetify-lzjyu0p1p-vuetifyjs1.vercel.app/en/getting-started/installation/)
![image](https://user-images.githubusercontent.com/16421948/119959963-d3ff3300-bfe7-11eb-8493-1b1cea945eb5.png)
The text here is supposed to be black unless it's an active route.

2021-05-28 09:08 UTC, Tofandel commented
Okay let me see if I can fix that without an important keyword

2021-05-28 17:56 UTC, Tofandel commented
I think to solve this it would make sense to have a `color` prop and an `active-color` prop or to avoid a breaking change a `base-color` prop and `color` prop (which only applies when the list item is active)

2021-05-30 19:28 UTC, Tofandel commented
I removed the color class when the item is not active, which fixes the demonstrated issue

Also took the liberty of adding the base-color prop which is the prop that controls the color when it's not active (and the color prop defaults to it if its not set)

2021-05-31 12:50 UTC, KaelWD commented
This also changes icons to black when inactive:
![image](https://user-images.githubusercontent.com/16421948/120195821-85a99880-c262-11eb-9417-36cd975ce779.png)

![image](https://user-images.githubusercontent.com/16421948/120195835-87735c00-c262-11eb-8222-d88ad6fedd3c.png)

2021-05-31 14:11 UTC, Tofandel commented
I changed it to only inherit icon color if the base color is set

I also added a colorful example in the doc
![image](https://user-images.githubusercontent.com/6115458/120205961-e1f0c600-c22a-11eb-9384-3eefe96e2818.png)

2021-05-31 16:08 UTC, KaelWD approved these changes

2021-05-31 16:10 UTC, KaelWD approved these changes

2021-06-08 18:43 UTC, johnleider requested changes
I think the naming is confusing. If we have a visual change based upon the state of an item, it should have a name that reflects that.

Personally, I'd rather have the parent dictate a **color** and **active-color** and leave `v-list-item` alone.

I'm actively working on v3 lists and I'll chime in more as I experiment more.

2021-06-09 00:58 UTC, Tofandel commented
I agree that adding a `color` and `active-color` prop to the v-list would be a good idea to apply it to all the v-list-items

But it's a must to also be able to change the color of some of the list item individually, where you can override this

And sadly on the v-list-item the naming can't be changed, it would be a big breaking change

2021-06-09 10:49 UTC, KaelWD commented
`active-color` can't be done in v2 without being a breaking change, I'm ok with this as a stopgap then change it again in v3. 

> I'd rather have the parent dictate a color and active-color and leave v-list-item alone.

There does need to be some way to change the colour of an individual item imo

2021-06-11 07:40 UTC, KaelWD commented
Hey @Tofandel, we discussed this in today's meeting and decided not to implement the new prop in v2 as it would be immediately deprecated. To fix #9285 in v2 we can accept removing the active class when not active though.

2021-06-11 08:58 UTC, Tofandel commented
So just the fix without the base-color prop?

2021-06-13 08:01 UTC, KaelWD commented on packages/vuetify/src/components/VList/VListItem.ts
> +  click (e: MouseEvent | KeyboardEvent): void
This shouldn't be necessary.

2021-06-14 18:21 UTC, johnleider approved these changes

2021-06-28 17:02 UTC, johnleider commented
Can you take a look at `v-list` as of v3-alpha.5 and compare the styling. We went with the prop name **active-color**.

2021-07-02 06:37 UTC, KaelWD approved these changes

2021-07-02 10:38 UTC, Tofandel commented
@johnleider The doc site doesn't seem to include it there https://next.vuetifyjs.com/en/components/application/ any other way to check except building it locally? Did you also add a similar snippet in the doc like: https://github.com/vuetifyjs/vuetify/pull/13719/commits/54f8d4f26e92175d6f337d188c4fbf79edddcc78 ?

2021-07-19 15:07 UTC, merged

2021-09-28 17:52 UTC, KaelWD commented
@Tofandel I'm going to have to revert this, `color` no longer affects active route links: #14186

Feel free to open a new PR if you have a solution that works for this case as well.

2021-09-28 19:11 UTC, Tofandel commented
@KaelWD that seems weird, isn't `this.isActive` data true for router links? Because I swear this was working

2021-09-28 19:21 UTC, Tofandel commented
So yeah this.isActive is false even if the link is current is this normal? Isn't there something missing in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/routable/index.ts

2021-09-28 19:33 UTC, Tofandel commented
One workaround is to check for the activeClass on the element instead of the isActive on every route change (or to set the isActive to true) because there doesn't seem to be any event or data available to save this externally in vue router..

2021-09-28 19:38 UTC, Tofandel commented
Well there you go.. It's already implemented https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/routable/index.ts#L153 The toggle function is empty and should be `this.isActive = true`

2021-09-28 19:40 UTC, Tofandel commented
@KaelWD So if you can do it quickly you can rerevert and change the line in the routable mixin, otherwise I'll make a new PR

2021-09-28 21:09 UTC, Tofandel commented
Indeed made a new PR, the onRouteChange should be called on mounted, as for the activeClass to set it back to false no need, you actually just need to call toggle, only if the class boolean is different than the isActive value, effectively trully reflecting isActive on every route change
The toggle also needs to be redefined in the VListItem because it's overriden by the groupable mixin