feat(theme): theme prop is now available on each component
vuetifyjs/vuetify pull request #13718
Opened 2021-05-27 16:01 UTC by nekosaur

## Description

add `theme` prop to each component so that it can override provided value and start new context for it and all children

**NOTE** this will add two computed variables for every component. there is no way of conditionally providing values

## TODO
- Make sure documentation is up-to-date and correct

## Motivation and Context

## How Has This Been Tested?

playground

## Markup:

<details>

```vue
<template>
  <v-app class="fill-height">
    <v-card :theme="theme" title="foo" subtitle="bar">
      <v-btn @click="theme = theme === 'light' ? 'dark' : 'light'">toggle</v-btn>
    </v-card>

    <v-card theme="dark" title="foo" subtitle="foo" color="purple-darken-2" append-icon="$close" />

    <v-theme-provider theme="dark">
      <v-card title="foo" subtitle="bar" class="ma-10" />
    </v-theme-provider>

    <v-card theme="dark" title="first">
      <v-card theme="light" title="second" class="ma-5">
        <v-card theme="dark" title="third" class="ma-5" />
      </v-card>
    </v-card>
  </v-app>
</template>

<script>
  import { ref } from 'vue'

  export default {
    name: 'Playground',
    setup () {
      const theme = ref('light')

      return { theme }
    },
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-05-27 17:11 UTC, johnleider reviewed
Code looks good. Feedback is here https://discord.com/channels/340160225338195969/519331123239583755/847520162365833216

2021-05-27 17:53 UTC, glen-84 commented
Closes #13288. (?)

2021-05-29 23:52 UTC, johnleider requested changes
Looks good. Any api-generator updates that need to be made?

2021-05-29 23:52 UTC, johnleider commented on packages/docs/src/pages/en/features/theme.md
> +Most components support the **theme** prop. When used, a new context will be created for the specific component and all of its children. In the example below the button will be using the **dark** the
```suggestion
Most components support the **theme** prop. When used, a new context is created for _that_ specific component and **all** of its children. In the following example, the [v-btn](/components/buttons/) uses the **dark** theme applied by its parent [v-card](/components/cards/).
```

2021-05-30 07:58 UTC, nekosaur commented on packages/docs/src/pages/en/components/theme-providers.md
> +By default `v-theme-provider` will act as a renderless component, and simply provide a new theme context to all of its children. However if you use the **with-background** prop, it will render a `div
1. The link for renderless component goes to page on render functions, which does not contain any specific information about the concept of renderless components
2. Is it relevant for the user that theme-provider uses provide/inject?

2021-05-31 20:52 UTC, johnleider commented on packages/docs/src/pages/en/components/theme-providers.md
> +By default `v-theme-provider` will act as a renderless component, and simply provide a new theme context to all of its children. However if you use the **with-background** prop, it will render a `div
1. Thought they were the same. We can update the page link or remove it entirely if it doesn't make sense
2. It introduces the user to a concept we use throughout Vuetify 3
3. Don't understand but if it's just a language update, what should it change to?

2021-05-31 20:59 UTC, nekosaur commented on packages/docs/src/pages/en/components/theme-providers.md
> +By default `v-theme-provider` will act as a renderless component, and simply provide a new theme context to all of its children. However if you use the **with-background** prop, it will render a `div
1. I'd say remove. I don't think official vue docs talk about renderless anywhere
2. Not sure if this is the place to do it
3. `When you use the with-background prop the v-theme-provider will render a div and apply the background color or something something something`

2021-06-01 14:07 UTC, johnleider commented on packages/docs/src/pages/en/components/theme-providers.md
> +By default `v-theme-provider` will act as a renderless component, and simply provide a new theme context to all of its children. However if you use the **with-background** prop, it will render a `div
1. 👍 
2. Okay, I'll defer to your judgement
3. `When using the **with-background** prop, the `v-theme-provider` renders a `<div>` element and applies the specified theme's background color to the element.

2021-06-01 16:22 UTC, johnleider requested changes

2021-06-01 16:22 UTC, johnleider commented on packages/docs/src/pages/en/components/theme-providers.md
> +By default, `v-theme-provider` is a renderless component that allows you to change the applied theme for all of its children. When using the **with-background** prop, the `v-theme-provider` will wrap
```suggestion
By default, `v-theme-provider` is a renderless component that allows you to change the applied theme for all of its children. When using the **with-background** prop, the `v-theme-provider` wraps its children in a `<div>` element and applies selected **theme's** background color.
```

2021-06-01 16:25 UTC, johnleider approved these changes

2021-06-01 16:28 UTC, merged