Typo
vuetifyjs/vuetify pull request #13890
Opened 2021-07-06 11:38 UTC by rochdiNassah

## Description

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-07-06 12:00 UTC, jacekkarczmarczyk submitted a review, later dismissed

2021-07-06 12:03 UTC, KaelWD commented
That doesn't make any sense either, is it supposed to say "throw on a `role="img"` attribute"?

"The attribute and the element are added" is nonsense too.

2021-07-06 12:07 UTC, KaelWD commented
> you need to provide a text alternative inside a (or similar) element

This whole page is cooked, who wrote it?

2021-07-09 15:15 UTC, johnleider commented
I hate this entire sentence as it stands. Let's either rewrite what it says or close this PR.

2021-07-28 15:11 UTC, johnleider requested changes

2021-07-28 15:11 UTC, johnleider commented on packages/docs/src/pages/en/components/icons.md
> +If your icon has semantic meaning, all you need to do is throw an attribute.The attribute and the element are added so that your icons are properly accessible.`role="img"<v-icon>`.
```suggestion
Apply accessibility attributes to the [v-icon](/components/icons/), such as `role="img"`, to the component to give it a semantic meaning.
```

2021-07-28 23:31 UTC, johnleider commented on packages/docs/src/pages/en/components/icons.md
> +Apply accessibility attributes to the [v-icon](/components/icons/), such as `role="img"`, to the component to give it a semantic meaning.
```suggestion
Apply accessibility attributes to the [v-icon](/components/icons/) component, such as `role="img"`, to give it a semantic meaning.
```

2021-07-28 23:33 UTC, johnleider approved these changes

2021-07-28 23:33 UTC, merged