test: add ability to create percy snapshots
vuetifyjs/vuetify pull request #13937
Opened 2021-07-18 11:17 UTC by nekosaur

## Description

adds percy integration so that we can have visual snapshots.

environment variable PERCY_TOKEN needs to be set before cy:run script is run (tests will still run but snapshots will not be taken or sent to percy)

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-08-14 22:57 UTC, johnleider requested changes

2021-08-14 22:57 UTC, johnleider commented on packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.cy.tsx
> +      <CenteredGrid width="200px">
Can we put this in CenteredGrid.tsx?

2021-08-14 22:57 UTC, johnleider commented on packages/vuetify/src/components/VPagination/__tests__/VPagination.spec.cy.tsx
> +      <VPagination length={3} />
```suggestion
      <VPagination length={ 3 } />
```

2021-08-24 14:01 UTC, KaelWD approved these changes

2021-08-24 14:05 UTC, merged