fix(VStepperStep): editable step tab navigation
vuetifyjs/vuetify pull request #14036
Opened 2021-08-07 14:33 UTC by lentyaevpk

## Description

Added tab navigation for editable stepper steps.
Fixes #14022 

## How Has This Been Tested?

Visually 

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-stepper>
    <v-stepper-header>
      <v-stepper-step
        editable
        step="1"
      >
        Select campaign settings
      </v-stepper-step>

      <v-divider></v-divider>

      <v-stepper-step
        editable
        step="2"
      >
        Create an ad group
      </v-stepper-step>

      <v-divider></v-divider>

      <v-stepper-step
        step="3"
        editable
      >
        Create an ad
      </v-stepper-step>
    </v-stepper-header>
  </v-stepper>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-11-29 18:05 UTC, johnleider requested changes

2021-11-29 18:05 UTC, johnleider commented on packages/vuetify/src/components/VStepper/VStepperStep.ts
> +      if (e.keyCode === 32) {
use https://github.com/vuetifyjs/vuetify/blob/3171d6f460ef41758817d54f18e20d6196ef05fb/packages/vuetify/src/util/helpers.ts#L200

2021-12-05 10:32 UTC, lentyaevpk commented on packages/vuetify/src/components/VStepper/VStepperStep.ts
> +      if (e.keyCode === 32) {
Done

2021-12-07 17:19 UTC, johnleider approved these changes

2021-12-07 17:20 UTC, merged