test(VBadge): cypress spec
vuetifyjs/vuetify pull request #14089
Opened 2021-08-25 21:38 UTC by ElijahKotyluk

## Description

  - Added RTL support
  - Added Theme support

## Motivation and Context

Provide e2e testing for `VBadge`.

## How Has This Been Tested?

Cypress
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-12-03 03:01 UTC, johnleider approved these changes

2022-02-02 21:09 UTC, johnleider requested changes

2022-02-02 21:09 UTC, johnleider commented on packages/vuetify/src/components/VBadge/VBadge.tsx
> +import { useRtl } from '@/composables/rtl'
move under // Composables

2022-02-02 21:09 UTC, johnleider commented on packages/vuetify/src/components/VBadge/VBadge.tsx
> +    const { roundedClasses } = useRounded(props, 'v-badge')
```suggestion
    const { roundedClasses } = useRounded(props)
```

2022-02-02 21:09 UTC, johnleider commented on packages/vuetify/src/components/VBadge/VBadge.tsx
> +    const { themeClasses } = useTheme()
```suggestion
    const { themeClasses } = useTheme(props)
```

2022-02-03 03:21 UTC, ElijahKotyluk commented on packages/vuetify/src/components/VBadge/VBadge.tsx
> +    const { themeClasses } = useTheme()
`useTheme()` no longer takes props as an argument.

2022-02-03 15:57 UTC, johnleider approved these changes

2022-02-22 20:22 UTC, merged