chore: add getCurrentInstance utility function
vuetifyjs/vuetify pull request #14140
Opened 2021-09-08 21:39 UTC by johnleider

## Description

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-09-09 12:16 UTC, blalan05 commented
The Hydration composable also uses getCurrentInstance, it could also benefit from using this util.

2021-09-09 14:41 UTC, KaelWD requested changes

2021-09-09 14:41 UTC, KaelWD commented on packages/vuetify/src/util/getCurrentInstance.ts
> +  if (!vm) consoleError(`${name} ${message}`)
Throw

2021-09-14 00:09 UTC, johnleider commented on packages/vuetify/src/util/useRender.ts
> +  const vm = getCurrentInstance('useRender') as any
it was there before and it complains if it's not there now

2021-09-14 23:31 UTC, merged