fix(VField): don't show gap when missing label
vuetifyjs/vuetify pull request #14486
Opened 2021-12-09 13:59 UTC by LucianHij

## Description
Handling the case when label is missing or it has falsy value
I am not aware of any open issue that this PR resolves. It resolves an issue that we discussed on the discord chat. 

## Motivation and Context
The layout is broken when using outlined variant. The notch is present and the border is interrupted with white space.

```vue
<template>
  <v-app>
    <v-container>
      <v-text-field
        v-model="something"
        variant="outlined"
        label="Something"
      />
      <v-text-field
        v-model="something"
        variant="outlined"
        label=""
      />
    </v-container>
  </v-app>
</template>

<script>
export default {
  name: "Playground",
  setup() {
    return {
      something: "",
    };
  },
};
</script>
```
</details>

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2021-12-10 16:25 UTC, johnleider requested changes
Since it's reused so much, create a computed property:

```ts
const hasLabel = computed(() => !props.singleLine && !!label)
```

and then use `hasLabel.value` throughout.

2021-12-10 21:24 UTC, LucianHij commented
> Since it's reused so much, create a computed property:
> 
> 
> 
> ```ts
> 
> const hasLabel = computed(() => !props.singleLine && !!label)
> 
> ```
> 
> 
> 
> and then use `hasLabel.value` throughout.

I will address it tomorrow

2021-12-13 12:02 UTC, KaelWD commented on packages/vuetify/src/components/VField/VField.tsx
> +    const hasLabel = computed(() => !props.singleLine && !!props.label)
```suggestion
    const hasLabel = computed(() => !props.singleLine && !!(props.label || slots.label))
```

2021-12-13 18:44 UTC, johnleider approved these changes

2021-12-14 07:00 UTC, KaelWD approved these changes

2021-12-14 07:01 UTC, merged