fix(VAutocomplete): update search value for mobile
vuetifyjs/vuetify pull request #15025
Opened 2022-05-01 20:21 UTC by tibnor

## Motivation and Context

VAutocomplete only filters complete waits for words to be completed on Android. The input of the inner VTextField of VAutocomplete is binded with a v-model. When using an android phone with autocomplete keyboard (GBoard) the value is first emitted when a word is completed. For instance if you write "House" v-model will first be updated when the word is completed and not on "H" -> "Ho" -> "Hou"... This means that VAutoComplete only filters on completed words. 

## Description
This pull request changes the databinding of VTextField in VAutoComplete from v-model into `@input` and `:modelValue`. `@input` is emitted on every key, while v-model waits for a word to be completed when using autocomplete on android keyboards. 

## How Has This Been Tested?
The code has been tested visually.

## Markup:

<details>

```vue
<template>
  <v-autocomplete :items="items" />
</template>

<script>
  export default {
    name: 'Playground',
    data: () => ({
      items: [
        {
          value: 'foo',
          title: 'Foo',
        },
        {
          value: 'bar2',
          title: 'Foo',
        },
        {
          value: 'baz',
          title: 'Baz',
        },
      ],
    }),
  }
</script>

```
</details>

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ x ] The PR title is no longer than 64 characters.
- [ x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x ] My code follows the code style of this project.
- [ x ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2022-05-04 11:18 UTC, KaelWD commented
Weird https://github.com/vuejs/vue/issues/9777#issuecomment-478831263

2022-05-04 11:19 UTC, KaelWD requested changes
This probably applies to combobox too

2022-05-04 11:28 UTC, tibnor commented
@KaelWD would you like the PR to include a fix for combobox to before you approve this PR?

2022-05-04 11:31 UTC, KaelWD commented
Yes please

2022-05-04 11:53 UTC, tibnor commented
@KaelWD: Here you are, now it is updated in VCombobox as well :-)

2022-05-04 17:29 UTC, merged

2023-10-23 04:56 UTC, yuwu9145 commented
I think this breaks the keyboard that's using IME composition model, e.g. Chinese keyboard

https://github.com/vuetifyjs/vuetify/assets/5698884/44c81f2a-d354-44cf-b15c-11e9df0b0da9

composition session events should be left to system keyboard to handle.

Also, I tried Gboard, maybe I missed something, but latest version Gboard doesn't have that underline composition suggestions anymore.

If this was true, this PR should be rolled back and consistently use `v-model`