fix(VRow): missing values, types
vuetifyjs/vuetify pull request #15586
Opened 2022-08-06 11:29 UTC by nekosaur

closes #15581

## Description

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-row justify="space-evenly" align-content="space-evenly"></v-row>
  </v-app>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2022-08-09 17:16 UTC, johnleider approved these changes

2022-08-09 18:36 UTC, KaelWD requested changes
`justify-content: stretch` doesn't exist in flexbox

2022-08-17 15:16 UTC, KaelWD approved these changes

2022-08-17 15:17 UTC, johnleider approved these changes

2022-08-17 15:22 UTC, merged