add slot:item in v-breadcrumbs
vuetifyjs/vuetify pull request #15743
Opened 2022-09-06 19:25 UTC by samehdoush

## Description
 fixes #15742

## Motivation and Context
Add v-slot:item to v-breadcrumbs

## How Has This Been Tested?

## Markup:

  ```
           <v-breadcrumbs tag="ul"  :items="breadcrumbs">
                        <template v-slot:prepend>
                            <v-icon size="small" icon="mdi-vuetify"></v-icon>
                        </template>
                        <template v-slot:item="{ item }">
                      
                            <v-breadcrumbs-item tag="li" :disabled="item.disabled">
                                {{ item.title.toUpperCase() }}
                            </v-breadcrumbs-item>
        
                        </template>
                    </v-breadcrumbs>
  ```

2022-09-07 07:29 UTC, ilham89 commented
ok nice!

2022-12-07 16:06 UTC, johnleider requested changes

2022-12-07 16:06 UTC, johnleider commented on packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx
> +                ? slots.item?.({ item: item })
```suggestion
                ? slots.item.({ item, index })
```

2022-12-07 16:06 UTC, johnleider commented on packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx
> +                />)
```suggestion
                : (
                  <VBreadcrumbsItem
                    key={index}
                    disabled={index >= array.length - 1}
                    { ...(typeof item === 'string' ? { title: item } : item)}
                    v-slots={{
                      default: slots.title ? () => slots.title.({ item, index }) : undefined,
                    } }
                  />
                )
```

2023-01-23 15:20 UTC, johnleider requested changes

2023-01-23 15:20 UTC, johnleider commented on packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx
> +              }
```suggestion
              { slots.item?.({ item, index }) ?? (
                  <VBreadcrumbsItem
                    key={ index }
                    disabled={ index >= array.length - 1 }
                    { ...(typeof item === 'string' ? { title: item } : item)}
                    v-slots={{
                      default: slots.title ? () => slots.title.({ item, index }) : undefined,
                    } }
                  />
                )
              }
```

2023-01-26 16:13 UTC, johnleider requested changes
My suggested commit wasn't spaced properly and I'm having issues cloning this for whatever reason. Could you resolve the lint issues please? Thank you

2023-06-19 19:59 UTC, johnleider approved these changes

2023-06-19 20:00 UTC, merged