fix(VAutocomplete): prevent mutate value in VTextField
vuetifyjs/vuetify pull request #15768
Opened 2022-09-10 03:18 UTC by yuwu9145

fixes #15756

## Description

## Motivation and Context

## How Has This Been Tested?

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

2022-09-15 08:10 UTC, KaelWD commented
This causes #14009 again. We need to show selections and the input side-by-side like v2 does.

2022-09-15 23:22 UTC, yuwu9145 commented
Thanks @KaelWD , I tried that "side-by-side" already, just I wasn't sure whether that was the right solution so I pushed a rather simple fix in this PR.

I can try it again so leave it to me.

2022-09-17 04:57 UTC, yuwu9145 commented
@KaelWD changes have been made to cover:

- For plain text selection (no slot): input field displays as absolute so it can cover selected text
- For selection slot is applied: display selection slot and the input side-by-side like v2 does

2022-10-04 15:08 UTC, johnleider requested changes
This should also apply to VSelect and VCombobox.

2022-10-04 15:08 UTC, johnleider commented on packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass
> +  &--slection-slot
```suggestion
  &--selection-slot
```

2022-10-08 04:44 UTC, yuwu9145 commented
Hi @johnleider 

Maybe I missed something, but as per my understanding at this stage. It does not seem to be necessary to apply this effect to `VSelect` and `VCombobox`:
- The root cause of this issue is `input` tag sometimes show over selection slot when there was manual user input, so input value looks overrides selection slot
- For VSelect, its `input` tag is always hidden when selected and VSelect should be designed to disallow any manual user input. Therefore, `input` tag cause no issue here.
- For VCombobox, its current behaviour looks fine.Its input tag always displays after selected items/slots. So also no issue in this senario.

I have updated sample markup to include `VCombobox` and `VSelect`. Feel free to leave further feedback :)

2022-10-13 19:18 UTC, johnleider approved these changes

2022-10-13 19:19 UTC, merged