fix: parse all colors to rgba objects instead of numbers
vuetifyjs/vuetify pull request #16052
Opened 2022-11-09 08:54 UTC by KaelWD

fixes #16045

2022-11-09 09:10 UTC, jacekkarczmarczyk commented on packages/vuetify/src/util/colorUtils.ts
> +export function HSVAtoRGBA (hsva: HSV): RGB {
`HSVtoRGB`?

2022-11-09 09:10 UTC, jacekkarczmarczyk commented on packages/vuetify/src/util/colorUtils.ts
>    return `rgba(${rgba.r}, ${rgba.g}, ${rgba.b}, ${rgba.a})`
won't it end up with `rgba(N, N, N, )` if `.a` is undefined?

2022-11-14 21:43 UTC, johnleider requested changes
I didn't mark all of the instances of **a** existing but you get the point.

2022-11-14 21:43 UTC, johnleider commented on packages/vuetify/src/components/VColorPicker/VColorPicker.tsx
> +    const updateColor = (hsva: HSV) => {
should the variable name be hsv?

2022-11-14 21:43 UTC, johnleider commented on packages/vuetify/src/components/VColorPicker/util/index.ts
> +  let hsva: HSV | null = null
should variable name be hsv?

2022-11-14 21:43 UTC, johnleider commented on packages/vuetify/src/components/VColorPicker/util/index.ts
> +export function extractColor (color: HSV, input: any) {
small nitpick, should the color variable be hsv to match other naming conventions?

2022-11-14 21:43 UTC, johnleider commented on packages/vuetify/src/util/colorUtils.ts
> +export type HSL = { h: number, s: number, l: number, a?: number }
should a?: number be here?

2022-11-29 17:17 UTC, johnleider approved these changes

2022-12-06 15:23 UTC, merged