Update v-autocomplete.json
vuetifyjs/vuetify pull request #16545
Opened 2023-01-29 19:38 UTC by mohkermani

## Description

## Markup:

```vue

```

2023-01-29 19:47 UTC, mohkermani commented
improve doc v-autocomplete slotd

2023-01-29 21:52 UTC, MajesticPotatoe requested changes
Some other quick easy wins:
- prepend/append and prepend/append-item (same verbiage as prepend/append-inner)
- clear is just slot for `clearable` prop

2023-01-29 21:52 UTC, MajesticPotatoe commented on packages/api-generator/src/locale/en/v-autocomplete.json
> +    "prepend-inner": "Appends slot outside of input",
```suggestion
    "prepend-inner": "Slot to insert items inside the input and before input content",
```

2023-01-29 21:52 UTC, MajesticPotatoe commented on packages/api-generator/src/locale/en/v-autocomplete.json
> +    "append-inner": "Appends slot inside input",
```suggestion
    "append-inner": "Slot to insert items inside the input and after input content",
```

2023-02-20 13:23 UTC, MajesticPotatoe requested changes

2023-02-20 13:23 UTC, MajesticPotatoe commented on packages/api-generator/src/locale/en/v-autocomplete.json
> +    "no-data": "Slot shiwn when there is no autocomplete data"
```suggestion
    "no-data": "Slot shown when there is no autocomplete data"
```

2023-02-20 13:23 UTC, MajesticPotatoe commented on packages/api-generator/src/locale/en/v-autocomplete.json
> +    "details": "MISSING DESCRIPTION ([edit in github](https://github.com/vuetifyjs/vuetify/tree/next/packages/api-generator/src/locale/en/v-autocomplete.json))",
```suggestion
    "details": "MISSING DESCRIPTION ([edit in github](https://github.com/vuetifyjs/vuetify/tree/master/packages/api-generator/src/locale/en/v-autocomplete.json))",
```

2023-04-18 16:05 UTC, johnleider commented
These changes should occur in the components autocomplete is inheriting from:

![image](https://user-images.githubusercontent.com/9064066/232836771-8e0e73cd-31ce-4c78-a612-edd57fff6c94.png)

2023-06-26 13:32 UTC, MajesticPotatoe commented
@mohkermani  pulse check

2023-06-27 08:39 UTC, mohkermani commented
> @mohkermani pulse check
> @johnleider These changes should occur in the components autocomplete is inheriting from:

Actually I cannot find any of slot descriptions in main file for v-input. there's only detail.

/vuetify/packages/api-generator/src/locale/en/v-input.json :
```
...
  "slots": {
    "details": "MISSING DESCRIPTION ([edit in github](https://github.com/vuetifyjs/vuetify/tree/master/packages/api-generator/src/locale/en/v-input.json))"
  },
...
```

2023-06-27 11:58 UTC, MajesticPotatoe commented
> Actually I cannot find any of slot descriptions in main file for v-input. there's only detail.

locale files were renamed on `master`, v-input.json is now VInput.json

2023-06-27 12:22 UTC, mohkermani commented
> > Actually I cannot find any of slot descriptions in main file for v-input. there's only detail.
> 
> locale files were renamed on `master`, v-input.json is now VInput.json

@MajesticPotatoe It gets more complicated :D There's only "props", "events", and "exposed" sections in the master VInput.
[ new VInput](https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/VInput.json)

2023-06-27 12:25 UTC, MajesticPotatoe commented
> > > Actually I cannot find any of slot descriptions in main file for v-input. there's only detail.
> > 
> > 
> > locale files were renamed on `master`, v-input.json is now VInput.json
> 
> @MajesticPotatoe It gets more complicated :D There's only "props", "events", and "exposed" sections in the master VInput. [ new VInput](https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/VInput.json)

Then add it?
(I would fix merge conflicts first though before doing anything)

2023-07-17 17:10 UTC, closed without merging