feat(VDataTable): add class to header
vuetifyjs/vuetify pull request #16762
Opened 2023-02-23 09:19 UTC by Yumamama00

## Description
Closes #16648 

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-data-table
        :headers="headers"
        :items="desserts"
        item-value="name"
      />
    </v-container>
  </v-app>
</template>

<script setup>
  const headers = [
    {
      title: 'Dessert (100g serving)',
      align: 'start',
      key: 'name',
      sortable: false,
      class: 'text-primary',
    },
    { title: 'Calories', key: 'calories', class: ['bg-grey-lighten-3', 'text-secondary'] },
    { title: 'Fat (g)', key: 'fat' },
  ]

  const desserts = [
    {
      name: 'Frozen Yogurt',
      calories: 159,
      fat: 6.0,
    },
    {
      name: 'Ice cream sandwich',
      calories: 237,
      fat: 9.0,
    },
    {
      name: 'Eclair',
      calories: 262,
      fat: 16.0,
    },
  ]
</script>

```

2023-06-16 12:38 UTC, scscgit commented
Also what about `cellClass`?
* #17515

2023-07-17 17:20 UTC, johnleider requested changes

2023-07-17 17:20 UTC, johnleider commented on packages/vuetify/src/labs/VDataTable/VDataTableHeaders.tsx
> +import { convertToUnit, genericComponent, useRender, wrapInArray } from '@/util'
```suggestion
import { convertToUnit, genericComponent, useRender } from '@/util'
```

2023-07-17 17:20 UTC, johnleider commented on packages/vuetify/src/labs/VDataTable/VDataTableHeaders.tsx
> +            ...wrapInArray(column.class),
```suggestion
            column.class,
```

2023-07-17 17:20 UTC, johnleider commented on packages/vuetify/src/labs/VDataTable/types.ts
> +  class?: string | string[]
```suggestion
  class?: any
```

2023-07-17 17:21 UTC, johnleider commented
Features go to the dev branch

2023-08-13 06:28 UTC, Yumamama00 commented
Thanks for the review. Fixed.

2023-08-13 07:50 UTC, Yumamama00 commented
> Also what about `cellClass`?
> 
> * [[Feature Request] Add custom css class to table headers and table columns  #17515](https://github.com/vuetifyjs/vuetify/issues/17515)

cellClass was addressed separately in the following PR.
https://github.com/vuetifyjs/vuetify/pull/18038

2023-09-27 22:08 UTC, websitevirtuoso commented
Long time without feedback. Can we check it? @johnleider

2023-09-28 18:44 UTC, johnleider commented
Anything not tagged for v3.4 milestone is very low priority atm.

2023-11-03 15:57 UTC, closed without merging

2023-11-03 15:57 UTC, KaelWD commented
Replaced by #18589