Update v-overlay:json
vuetifyjs/vuetify pull request #16779
Opened 2023-02-25 21:33 UTC by webdevnerdstuff

Added `scrim`, `persistent`, and `noClickAnimation` prop descriptions. 

Referenced: 
https://github.com/vuetifyjs/vuetify/issues/16580
https://v2.vuetifyjs.com/en/api/v-dialog/#props

## Description

## Markup:

```vue

```

2023-02-28 12:34 UTC, KaelWD requested changes

2023-02-28 12:34 UTC, KaelWD commented on packages/api-generator/src/locale/en/v-overlay.json
> +    "click:outside": "Event that fires when clicking outside an active dialog.",
```suggestion
    "click:outside": "Event that fires when clicking outside an active overlay.",
```

2023-02-28 12:34 UTC, KaelWD commented on packages/api-generator/src/locale/en/v-overlay.json
> +    "noClickAnimation": "Disables the bounce effect when clicking outside of a `v-dialog`'s content when using the persistent prop.",
```suggestion
    "noClickAnimation": "Disables the bounce effect when clicking outside of the content element when using the persistent prop.",
```

2023-03-01 18:11 UTC, webdevnerdstuff commented
Suggestions committed.

2023-03-21 14:47 UTC, merged