Update v-navigation-drawer.json
vuetifyjs/vuetify pull request #16782
Opened 2023-02-25 21:59 UTC by webdevnerdstuff

## Description
Added `railWidth`, `width`, and `location` descriptions.

## Markup:
n/a

2023-02-28 12:39 UTC, KaelWD requested changes

2023-02-28 12:39 UTC, KaelWD commented on packages/api-generator/src/locale/en/v-navigation-drawer.json
> +    "railWidth": "Designates the width assigned when the `rail` prop is turned on",
```suggestion
    "railWidth": "Sets the width for the component when `rail` is enabled.",
```

2023-02-28 12:39 UTC, KaelWD commented on packages/api-generator/src/locale/en/v-navigation-drawer.json
> +    "location": "Apply the position navigation drawer on the screen.",
```suggestion
    "location": "Sets where the drawer should appear in the layout.",
```

2023-03-01 18:10 UTC, webdevnerdstuff commented
Suggestions committed.

2023-04-18 16:59 UTC, johnleider requested changes

2023-04-18 16:59 UTC, johnleider commented on packages/api-generator/src/locale/en/v-navigation-drawer.json
> +    "width": "Sets the width for the component.",
```suggestion
```

This already exists within **generic.json**

2023-04-18 16:59 UTC, johnleider commented on packages/api-generator/src/locale/en/v-navigation-drawer.json
> +    "location": "Sets where the drawer should appear in the layout.",
```suggestion
    "location": "Sets the drawer's location within the layout.",
```

2023-04-24 14:35 UTC, johnleider approved these changes

2023-04-24 14:36 UTC, merged