Update v-navigation-drawer.json
vuetifyjs/vuetify pull request #16970
Opened 2023-03-21 13:10 UTC by iabhishekraj

Added description of `rail` property of `v-navigation-drawer`

## Description

## Markup:

```vue

```

2023-04-18 17:45 UTC, johnleider submitted a review, later dismissed

2023-04-18 17:45 UTC, johnleider commented on packages/api-generator/src/locale/en/v-navigation-drawer.json
> +    "rail": "If true, it will show a condensed version else an expanded version.",
```suggestion
    "rail": "Sets the component width to the value of the [rail-width](#props-rail-width) property.",
```

2023-06-26 13:07 UTC, MajesticPotatoe requested changes
Resolve conflicts
(file name has changed on master from v-navigation-drawer.json -> VNavigationDrawer.json)

2023-07-11 22:12 UTC, johnleider approved these changes

2023-07-11 22:12 UTC, merged