Update upgrade-guide.md
vuetifyjs/vuetify pull request #17160
Opened 2023-04-16 03:50 UTC by NavidMitchell

Add a warning about missing components in Vuetify 3, that were available in Vuetify 2. This cost me a considerable amount of time.

## Description

## Markup:

```vue

```

2023-04-18 15:07 UTC, johnleider requested changes

2023-04-18 15:07 UTC, johnleider commented on packages/docs/src/pages/en/getting-started/upgrade-guide.md
> +  Addtionally, not all components available for Vuetify 2 have been migrated to Vuetify 3. Most notibly the v-data-table. However, some are available in [Vuetify Labs](https://vuetifyjs.com/en/labs/i
```suggestion
  Additionally, not all components available for Vuetify 2 have been migrated to Vuetify 3; most notably the v-data-table. However, some are available in [Vuetify Labs](https://vuetifyjs.com/en/labs/introduction/). 
```

2023-04-19 05:29 UTC, NavidMitchell commented
Applied requested changes. Thank you!

2023-04-19 12:27 UTC, MajesticPotatoe requested changes
Separate out into its own alert. Reword and list out pending components.

2023-04-21 11:59 UTC, MajesticPotatoe submitted a review, later dismissed

2023-04-21 12:08 UTC, MajesticPotatoe approved these changes

2023-04-21 12:08 UTC, merged