fix(VListItem): add anchor title
vuetifyjs/vuetify pull request #17940
Opened 2023-08-01 20:59 UTC by bogdanciuca

## Description

`VListItem` anchor is missing the `title` prop. Fixes: https://github.com/vuetifyjs/vuetify/issues/17908

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-card>
        <v-list>
          <v-list-item
            v-for="(item, index) in items"
            :key="index"
            :title="item.title"
            :href="item.href"
          />
        </v-list>
      </v-card>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const items = ref([
    {
      title: 'Vuetify',
      href: 'https://vuetifyjs.com/en/',
    },
    {
      title: 'Vue',
      href: 'https://vuejs.org/',
    },
  ])
</script>
```

2023-08-01 23:45 UTC, johnleider requested changes

2023-08-01 23:45 UTC, johnleider commented on packages/vuetify/src/components/VList/VListItem.tsx
> +          title={ slots.title?.({ title: props.title }) ?? props.title }
I've never seen a slot used like this before. It also means you'd have to update the available slots for this component. I think it's safe for this to simply equal props.title.

2023-08-08 20:10 UTC, johnleider approved these changes

2023-08-08 20:11 UTC, merged

2023-08-10 09:44 UTC, KaelWD commented
I'm reverting this, it adds `title="false"` if the title prop is not set and even if it is set you don't always want a tooltip.

2023-08-10 12:27 UTC, johnleider commented
> I'm reverting this, it adds `title="false"` if the title prop is not set and even if it is set you don't always want a tooltip.

Then why not adjust it to be undefined if not set instead of reverting it?

2023-08-10 12:53 UTC, KaelWD commented
Because the second part of that sentence.

2023-08-15 10:05 UTC, chunlampang commented
Because of `title="false`, when hover the list item, it showing "false" by the default html title attribute.