fix(VSelect/VAutocomplete/VCombobox): respect virtual scroll when focus last and first
vuetifyjs/vuetify pull request #18404
Opened 2023-10-05 10:50 UTC by yuwu9145

fixes #18383

## Description

## Markup:

```vue
<template>
  <v-card>
    <v-container fluid>
      <v-combobox
        v-model="values"
        :items="items"
        label="Default"
      />
      <v-autocomplete
        v-model="values"
        :items="items"
        label="Default"
      />
      <VSelect :items="items" v-model="values"/>
    </v-container>
  </v-card>
</template>

<script>
  export default {
    data: () => ({
      items: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
      ],
      values: '1',
    }),
  }
</script>

```

2023-10-09 18:03 UTC, johnleider requested changes
Everything looks good for Autocomplete and Combobox but Select is still having some issues. If you focus it and press "up" it will open the Select and then focuses number 12.
![keyboard](https://github.com/vuetifyjs/vuetify/assets/9064066/71c9f7c1-db23-438e-8591-d07091aa2236)

2023-10-17 00:16 UTC, yuwu9145 commented on packages/vuetify/src/composables/virtual.ts
> +      watchEffect(() => {
Integrating with virtual scroll introduce race conditions, and also for arrow up/down keys, there are duplicated keydown handlers from multiple components makes race conditions even worse. Big refactoring is inevitable

2024-02-01 11:51 UTC, yuwu9145 commented
@KaelWD It's a big time-consuming/complex fix, would be good to get your advice & insights when you got time

2026-08-15 21:03 UTC, J-Sek commented
closing in favor of #23031

2026-08-15 21:03 UTC, closed without merging