fix(VDatePicker): fix range selection crossing DST
vuetifyjs/vuetify pull request #19378
Opened 2024-03-12 12:38 UTC by alexkunin

## Description

fixes #19313

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      {{ data }}
      <v-date-picker v-model="data" multiple="range"></v-date-picker>
    </v-container>
  </v-app>
</template>

<script>
  import { ref } from 'vue'

  export default {
    name: 'Playground',
    setup () {
      return {
        data: ref(null)
      }
    },
  }   
</script>
```

2024-03-12 12:43 UTC, KaelWD requested changes
This has to be compatible with https://github.com/dmtrKovalenko/date-io/blob/master/packages/core/IUtils.d.ts#L122

2024-03-12 13:09 UTC, alexkunin commented
Fair point.

So, `Unit` should not be changed as it will change public API.

Using ad-hoc date calculations in the component it not an option too, as it does not allow to use adapter of choice in cases when non-built-in adapter is provided.

Possible solutions:

1. fix `getDiff` to use `Math.round` (still not sure if this should be done for all unit, or only for `'days'`)
    a) actually, this might not be the correct fix because its correctness depends on semantics: does `'days'` mean calendar days, or just 24 hours periods? tbf it feels like the latter is the case, and thus `getDiff` does not need 'fixing'

2. or change the way `VDatePicker` works with dates, i.e. maybe use UTC
    a) we can use UTC everywhere in the component, which may lead to many imcompatibilities
    b) or, we can change that single place where `getDiff` is used -- this should fix the bug and introduce the least amount of very localized possible incompatibilities

I think I'll stick with 2b.

2024-03-12 13:45 UTC, alexkunin commented
The solution turned out to be even simpler: don't use `getDiff` at all, just iterate over range of dates.
```ts
const datesInRange = []
  
for (let d = rangeStart.value; d <= rangeStop.value; d = adapter.addDays(d, 1)) {
  datesInRange.push(d)
}
  
model.value = datesInRange
```
So, instead of counting days (incorrectly) and then iterating over that count, I just iterate from starting date, add 1 day on each iteration, stop when target date is reached.

2024-03-15 22:37 UTC, johnleider commented
I fixed this in your other P.R.

2024-03-26 13:43 UTC, closed without merging