fix: make router useLink link reactive
vuetifyjs/vuetify pull request #19386
Opened 2024-03-12 21:42 UTC by Antti-Palola

## Description
If for example VCard to prop is evaluated as undefined and then changed, the changes were not be propagated to the href.

fixes #19300

Card link after enabling link (from undefined to page2)

| Before | After |
| -- | -- |
|  ![router-before](https://github.com/vuetifyjs/vuetify/assets/100124171/c5923da5-96d6-485f-94b0-9db76b30d118) | ![router-after](https://github.com/vuetifyjs/vuetify/assets/100124171/ebdf369e-950d-4d2d-a4e5-89c26ac492d7) |

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      Click button to toggle link state on list item
      <v-btn @click="setLink">Set link</v-btn>
      <v-list>
        <v-list-item :to="listLink" color="green">{{ `Link to ${listLink?.name}` }}</v-list-item>
        
      </v-list>
      <v-card :to="listLink">
        <v-card-title>Linked card</v-card-title>
        <v-card-text>{{ `Link to ${listLink?.name}` }}</v-card-text>
      </v-card>
    </v-container>
  </v-app>
</template>

<script>
  import { ref } from 'vue'
  export default {
    name: 'Playground',

    setup () {
      const listLink = ref(undefined)
      function setLink () {
        if (listLink.value) {
          listLink.value = undefined
        } else {
          listLink.value = { name: 'page2' }
        }
      }
      return {
        listLink,
        setLink,
      }
    },
  }
</script>

```

2024-03-13 06:57 UTC, Antti-Palola commented
The breadcrumbs cypress test is failing locally for me as well but I updated the Playground example to contain a breadcrumb too and it's working as it's supposed to.

2024-03-15 23:25 UTC, johnleider requested changes

2024-03-15 23:25 UTC, johnleider commented on packages/vuetify/src/composables/router.tsx
> +  const toPropRef = computed(() => props.to ? props.to : {})
This would be fine inside of linkProps.

2024-03-24 07:44 UTC, Antti-Palola commented on packages/vuetify/src/composables/router.tsx
> +  const toPropRef = computed(() => props.to ? props.to : {})
yeah, changed ✅

2024-03-26 13:45 UTC, johnleider approved these changes

2024-03-26 13:46 UTC, merged