feat(VSwitch, VSwitchBtn, VSwitchTrack)
vuetifyjs/vuetify pull request #19529
Opened 2024-04-02 14:20 UTC by De-Hann

Split VSwitch component into three smaller components

```vue
<template>
  <v-app>
    <v-container>
      <v-defaults-provider :defaults="{ VCheckboxBtn: { density: 'compact' } }">
        <v-checkbox-btn label="Button 1"></v-checkbox-btn>
        <v-checkbox-btn label="Button 2"></v-checkbox-btn>
        <v-checkbox-btn label="Button 3"></v-checkbox-btn>
      </v-defaults-provider>

      <v-checkbox-btn label="Button"></v-checkbox-btn>
      <v-checkbox label="Button"></v-checkbox>

      <v-switch :model-value="model" color="success" label="New Switch ON">
        <template v-slot:track-false>false</template>
        <template v-slot:track-true>true</template>
      </v-switch>

      <v-switch :model-value="model" color="success" label="New Switch ON"></v-switch>
      <v-switch color="success" label="New Switch NONE"></v-switch>
      <v-switch :model-value="!model" color="success" label="New Switch OFF"></v-switch>

      <v-switch-btn :model-value="model" label="Switch Btn ON"></v-switch-btn>
      <v-switch-btn  label="Switch Btn NONE"></v-switch-btn>
      <v-switch-btn :model-value="!model" label="Switch Btn OFF"></v-switch-btn>

      <v-defaults-provider :defaults="{ VSwitchBtn: { density: 'compact' } }">
        <v-switch-btn :model-value="model" color="success" label="Switch 1">
          <template v-slot:track-false>false</template>
          <template v-slot:track-true>true</template>
        </v-switch-btn>
        <v-switch-btn label="Switch 2" loading="warning"></v-switch-btn>
        <v-switch-btn :model-value="model" label="Switch 3"></v-switch-btn>
        <v-switch-btn :model-value="model" label="Switch 4"></v-switch-btn>
      </v-defaults-provider>
    </v-container>
  </v-app>
</template>

<script>
  export default {
    name: 'Playground',
    setup() {
      return {
      }
    },
    data () {
      return {
        model: true,
      }
    },
  }
</script>

```

2024-04-11 02:32 UTC, johnleider requested changes

2024-04-11 02:32 UTC, johnleider commented on .gitignore
> +# ignore yarn build files
is this needed for the PR?

2024-04-11 02:32 UTC, johnleider commented on packages/vuetify/src/components/VSwitch/VSwitchTrack.tsx
> +  model: Ref<boolean>
My intent for switch track was to clean-up the component. I don't think that it needs to have model support itself.

2024-04-11 02:32 UTC, johnleider commented on packages/vuetify/src/components/VSwitch/index.ts
> +export { VSwitchTrack } from './VSwitchTrack'
This doesn't need to be public

2026-07-02 12:40 UTC, J-Sek commented
This is possible with `@vuetify/v0` [Switch](https://0.vuetifyjs.com/components/forms/switch) component. Vuetify is going to adopt it, but I am not sure if we are going to expose the lower-level subcomponents. If the goal was primarily the control of the size, v4.1.0 shipped new `size` prop.

2026-07-02 12:40 UTC, closed without merging