fix(VField/VInput): centerAffix doesn't work for underlined/filled
vuetifyjs/vuetify pull request #20064
Opened 2024-06-27 01:05 UTC by yuwu9145

## Description

## Markup:

```vue
<template>
  <v-container class="pa-md-12 bg-grey">
    <v-row>
      <v-col cols="4">
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="solo"
          label="solo"
          variant="solo"
          center-affix
          single-line
        />
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="outlined"
          label="outlined"
          variant="outlined"
          center-affix
          single-line
        />
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="filled"
          label="filled"
          variant="filled"
          center-affix
          single-line
        />
        <v-text-field
          bg-color="white"
          clearable
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="underlined"
          variant="underlined"
          center-affix
          single-line
        />
      </v-col>
      <v-col cols="4">
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="solo"
          label="solo"
          variant="solo"
          single-line
        />
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="outlined"
          label="outlined"
          variant="outlined"
          single-line
        />
        <v-text-field
          bg-color="white"
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="filled"
          label="filled"
          variant="filled"
          single-line
        />
        <v-text-field
          bg-color="white"
          clearable
          prepend-icon="$vuetify"
          prepend-inner-icon="$vuetify"
          placeholder="underlined"
          variant="underlined"
          single-line
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
  import { ref } from 'vue'
</script>

```

2024-06-27 14:35 UTC, johnleider commented
Is there a collection of props that would move the label to the middle as well?
![image](https://github.com/vuetifyjs/vuetify/assets/9064066/35849330-0f01-4ebd-850e-7133f29106c1)

2024-06-28 04:11 UTC, yuwu9145 commented
> Is there a collection of props that would move the label to the middle as well? 

Need some additional fix to make sure label/input centre-aligned for underlined variant, same as v2 does
[v2 demo](https://codepen.io/yuchaosydney/pen/mdYgNJr?editors=101)
[v3 demo](https://play.vuetifyjs.com/#eNpVj88OgjAMh19l2VnkbiaJd99APBQoZEkpSxlEY3x3tylxXPbn+23t19tLz9KWF+eO64L6pI3H0RF4rGpWyqwFOJeO6dJO7MEyyg8l6PHhi94idRtUiqBBOtf6Gvda/4MVxAL7EC3coVAo1uV5M4QmNEl44MSOIM88nS0PhEX8tcHKlLnC5hrgXjaS7yymzGaMFn2SYP0+8EKUlvsHLDtZbw==)

2024-06-30 03:01 UTC, yuwu9145 commented
@johnleider See if you were satisfied with the API description/usage change, I will handle the technical part and make sure no regression

2024-07-01 15:38 UTC, johnleider commented
Looks good. Not related to anything you've done, but the prepend-inner icon is really tight on the edge of the input. Is that by design or not intentional?

2024-07-03 05:02 UTC, yuwu9145 commented
I think underlined variant is supposed to extend the content to edges, we have a little gap before prepend-inner, which is ok I guess.

Use slot to add a manual gap

<img width="286" alt="Screenshot 2024-07-03 at 3 00 43 pm" src="https://github.com/vuetifyjs/vuetify/assets/5698884/4feb3abd-197c-4056-903a-f3d565fd17e0">


```vue
<v-text-field
          bg-color="white"
          clearable
          prepend-icon="$vuetify"
          placeholder="underlined"
          label="underlined"
          variant="underlined"
          center-affix
        >
          <template #prepend-inner>
            <v-icon class="ml-3" icon="$vuetify" />
          </template>
        </v-text-field>
```

2024-07-03 18:27 UTC, johnleider requested changes

2024-07-03 18:27 UTC, johnleider commented on packages/vuetify/src/components/VInput/VInput.tsx
> +    default: false,
If default is false, can just do `centerAffix: Boolean` which defaults to false.

2024-07-03 18:27 UTC, johnleider commented on packages/vuetify/src/components/VField/VField.tsx
> +    default: false,
If default is false, can just do `centerAffix: Boolean` which defaults to false.

2024-07-09 16:16 UTC, johnleider approved these changes

2024-07-09 16:16 UTC, merged