feat(VOverlay): introduce MD3 scrim and shadow color variables and update `overlay-scrim-background`
vuetifyjs/vuetify pull request #20246
Opened 2024-07-30 07:02 UTC by BobYue-01

## Description

resolves #20244

Vuetify currently uses the Material Design 2 color system, which does not include a specific color variable for `overlay-scrim-background` required by components like dialogs. As a result, the following setting is used:
```sass
// components/VOverlay/_variables.scss
$overlay-scrim-background: rgb(var(--v-theme-on-surface)) !default;
```
In dark themes, the `on-surface` color is pure white (`#FFFFFF`), leading to a semi-transparent white overlay. This can be very glaring and does not comply with Material Design guidelines.

Material Design 3 (MD3) provides [dedicated color roles](https://m3.material.io/styles/color/roles) for Scrim and Shadow (`md.sys.color.scrim`, `md.sys.color.shadow`), both defaulting to pure black (`#000000`) in light and dark themes. Utilizing these variables for `$overlay-scrim-background` can enhance visual consistency and user experience, especially in dark themes.

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-btn text="toggle theme" @click="toggleTheme" />

      <v-dialog max-width="480">
        <template #activator="{ props: activatorProps }">
          <v-btn v-bind="activatorProps" text="Open Dialog" />
        </template>

        <template #default="{ isActive }">
          <v-card title="Dialog">
            <v-card-text> Lorem ipsum dolor sit amet. </v-card-text>

            <v-card-actions>
              <v-spacer />

              <v-btn text="toggle theme" @click="toggleTheme"/>

              <v-btn
                text="Close Dialog"
                @click="isActive.value = false"
              />
            </v-card-actions>
          </v-card>
        </template>
      </v-dialog>
    </v-container>
  </v-app>
</template>

<script setup>
  import { useTheme } from 'vuetify'

  const theme = useTheme()

  function toggleTheme () {
    theme.global.name.value = theme.global.current.value.dark ? 'light' : 'dark'
  }
</script>
```
[Vuetify Playground](https://play.vuetifyjs.com/#eNqdU8FO4zAQ/ZVR9hCQtuke9rCqCguCIxIcuFEOxpmkFo5t2eMCivrvTOImJFW5cImSmTcz772ZPLVZ8HJ57Vyxi5itsjVh47QgvNwYgPVuIZzrX/sPaQ0JZdAfQn3whQwQvtPFJiNb1xqBttjgJoMrqZV8HeOPh/CSqyf1pRLa1tCI98WbKmnL+L///myycQajBlbwS0hSO0HWM6wF560LKxiDD9037GfFI0l+KlNy3RzOjA707x0auO3pHGiOHZYTX07yKrESUXddWlDhupuAp4hI4UsgRRoZOsyagUbYoqN1CXfWYwPKhdhAabX1EBSBaJAK5jWFTqlN+3R6rQlHU/p8cEKin63kyLUfr/Z0nxttA36ZPPYZPCt2QkeEC6iEDkPLWbtB8ilVQ/K71X2h0tUNp92VzW67i6TTP1r9OkivHEFAiunPUI2znqCFGJIPsIfK2wZy/qVIVR958oQHBEoGsrwBfHaeslU0vR6YGHp2Dm0i2FcVtbYvQheGdz/aNMvI6D0aSsmiFP4V/kOuVb2lHFaQdxFmA3yYrCspYQ3Z/reJWveP508PREgK)

2024-07-30 07:29 UTC, BobYue-01 commented
The Jest CI tests failed, seemingly because extra on-* colors for scrim and shadow were automatically generated unnecessarily. Additionally, the test does not recognize the newly introduced scrim and shadow variables themselves. I am not very familiar with this and currently unable to resolve it.

2024-08-01 00:26 UTC, MajesticPotatoe requested changes
- [ ] rebase to `dev`

2024-12-22 19:14 UTC, J-Sek commented
We could move it to variables section `theme-scrim` as `theme-shadow`, but although it seems nice to comply with MD3 the framework would be just fine with hardcoded `#000 !default` and avoiding bloat even if these are just two CSS variables.

From the MD3 perspecive these are useful.. kinda. However I would expect Vuetify to comply by using efectively the same color, not by blindly following the spec and copying meaningless variables.

2025-04-26 17:16 UTC, J-Sek commented
covered by #21219

2025-04-26 17:16 UTC, closed without merging