docs(building-a-basic-nuxt-application-with-vuetify): add new blog post
vuetifyjs/vuetify pull request #20622
Opened 2024-10-26 19:29 UTC by johnleider

## Motivation and Context
New blog post

2024-10-27 08:27 UTC, userquin commented
I guess we should review and merge vuetify create pr about adding nuxt template and update the entry about creating and installing vuetify here.

2024-10-29 15:50 UTC, johnleider commented
> I guess we should review and merge vuetify create pr about adding nuxt template and update the entry about creating and installing vuetify here.

I've reviewed and approved what you have over there.

2025-02-20 22:56 UTC, wb-ts requested changes
Please take a look of the notes and try to update.

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +The app attribute has been added to the v-app-bar component and the v- footer component.
`v- footer` to `v-footer`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +![](https://cdn.vuetifyjs.com/docs/images/blog/building-a-basic-nuxt-application-with-vuetify/11.png){ height=500 }
remove `{ height=500 }`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +The footer is now displayed correctly, taking into account the height attri- bute specified within it.
`attri- bute` to `attribute`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +2. The products.vue page, which displays the products of our appli- cation.
`appli- cation` to `application`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +      <v-icon>mdi-apps</v-icon>
`<v-icon>mdi-apps</v-icon>`  to `<v-icon icon="mdi-apps" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-home</v-icon>
`<v-icon left>mdi-home</v-icon>` to `<v-icon icon="mdi-home"/>`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-cube-outline</v-icon>
`<v-icon left>mdi-cube-outline</v-icon>` to `<v-icon icon="mdi-cube-outline"/>`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-email</v-icon>
`<v-icon left>mdi-email</v-icon>` to `<v-icon icon="mdi-email"/>`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +The menu also needs to be linked to this reactive variable. To achieve this, Vuetify uses the v-model  attribute in the v-navigation-drawer  com- ponent. Many Vuetify components use the v-model attri
`com- ponent` to `component`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +Clicking on each navigation menu item is handled by the @click attribute, which is a shorthand for v-on:click  provided by Vue.js. We call the navigateTo(page) method, which displays the page specifi
`para- meter` to `parameter`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +![](https://cdn.vuetifyjs.com/docs/images/blog/building-a-basic-nuxt-application-with-vuetify/12.png){ height=500 }
remove `{ height=500 }`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +  <v-container class="fill-height d-flex flex-column align-center justify-center text-center">
remove classes which are not usable : `fill-height` and `text-center`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +    <v-icon size="64">mdi-cube-outline</v-icon>
`<v-icon size="64">mdi-cube-outline</v-icon>`  to `<v-icon size="64" icon="mdi-cube-outline" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +We therefore insert buttons in the form of icons into the application's tool- bar. The app.vue component becomes:
`tool- bar` to `toolbar`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +    <v-app-bar app color="primary" height="48">
remove `app` attribute.

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +      <v-toolbar-title class="text-h6 ml-3">
change `v-toolbar-title` to `v-app-bar-title`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +      <v-icon @click="drawer = !drawer">mdi-apps</v-icon>
`<v-icon @click="drawer = !drawer">mdi-apps</v-icon> ` to `<v-icon @click="drawer = !drawer" icon="mdi-apps" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +        <v-icon>mdi-home</v-icon>
`<v-icon>mdi-home</v-icon>` to `<v-icon icon="mdi-home" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +        <v-icon>mdi-cube-outline</v-icon>
`<v-icon>mdi-cube-outline</v-icon>` to `<v-icon icon="mdi-cube-outline" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +        <v-icon>mdi-email</v-icon>
`<v-icon>mdi-email</v-icon>` to `<v-icon icon="mdi-email" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-home</v-icon>
`<v-icon left>mdi-home</v-icon>` to `<v-icon icon="mdi-home" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-cube-outline</v-icon>
`<v-icon left>mdi-cube-outline</v-icon>` to `<v-icon icon="mdi-cube-outline" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +          <v-icon left>mdi-email</v-icon>
`<v-icon left>mdi-email</v-icon>` to `<v-icon icon="mdi-email" />`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +Vuetify offers the v-spacer component, which allows "pushing" the ele- ments that follow it to the right. The buttons will therefore be positioned on the right side of the toolbar.
`ele- ments` to `elements`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +To display the buttons, we use the v-btn component with the icon attri- bute. This attribute allows the button to be displayed in a circular shape, ac- cording to the icon it contains. The @click att
- `attri- bute` to `attribute`
- `ac- cording` to `according`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +![](https://cdn.vuetifyjs.com/docs/images/blog/building-a-basic-nuxt-application-with-vuetify/14.png){ height=500 }
remove `{ height=500 }`

2025-02-20 22:56 UTC, wb-ts commented on packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md
> +![](https://cdn.vuetifyjs.com/docs/images/blog/building-a-basic-nuxt-application-with-vuetify/15.png){ height=500 }
remove `{ height=500 }`

2025-02-21 19:08 UTC, merged